### ISSUE TITLE
DarkRP Enhancement Ideas

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1773]
I have made some suggestion to better up the darkrp mod, in my opinion there are just too much lacks in the gameexperience, either I love the mod too.
I would like to get some enhancements, If I am allowed to say that.
1 / 4 Ideas.

1.I would like to disable propspawn logging, but I'd like additionally to have hit logging active.
But I can only disable or enable the whole thing. I would be proud if that get's enhanced.
Even FAdmin should log tooluses either. Or maybe lockpick uses. A huge lack for me.

2. Savemethods: I would like to save doorgroups/fadmin settings I've created in a folder and not just save it to SQLite. SQLite just fucks up everything on my old servers. I had a lot of problems with it the last time and till now!
I would like to see savemethods like data or tmysql in the game.

3. Shipments or even weapons are working too basically In my opinion.
If you drop a weapon without ammonation and pick it up again it does have ammo again.
It should save clip1 and either clip2 instead of just giving the weapon back.
Also Shipments, drop a weapon without ammo like a rpg7, pick it up -> Ammo
i would suggest saving here too.

4. Decay times, sometimes props are falling through the map, I would suggest a check if that problem exists and then probably get them removed.
Also there should be a weapon/shipment decay time as shipments and weapons should'nt stay forever till a server crash on the server. this just produces lagg and does make the game unplayable.
(I know we could modify, but the mod shouldn't be build off modifying(I modified it already : just a suggestion for everyone to have a achievement) )

5. It should be configurable if death players can talk with voicechat and either chat while they dead, It really fucks up the roleplay in my mind.
I think a config option for this would just kick some kiddy nuts.
I love kicking kiddy nuts. (just hate them, they fuck every game I like ;)   )

I'm sorry for bother you with this suggestions, but I really would like to see some of them in the mod.
cmon at least 1/3 part .
I know the most parts of this get's declined, but atleast it should be made 1 change for a very very big DarkRP Mod fan.

Thank you anyways for reading till this line :P youre freaking great.

And thank you for the mod and updating it of course.

**Comment by Bo98** [comment]
> I would like to see savemethods like data or tmysql in the game.

tmysql support already exists.

> If you drop a weapon without ammonation and pick it up again it does have ammo again.

Depends on the weapon. It doesn't happen with default DarkRP weapons. I'm not sure how much can be done to workaround other weapons. What weapon pack are you using?

**Comment by FPtje** [comment]
1. Disable the individual FAdmin hooks with `hook.Remove`. I don't want to bloat up FAdmin too mucht
2. SQLite will always be more reliable then whatever hack I will put together myself. SQLite "just fucking up everything" is nonsense. Also, storing it in my own format makes it easier to modify by end users. That's something I don't want to happen because they can *and will* fuck it up. Another thing is that I'll be forced to put it in data, making it vulnerable for data reading exploits. All plenty of reasons to stick with relational databases.
3. This should not be happening unless you're using some funky ass weapon pack. I've seen weapon packs give ammo on pickup regardless of what I do in DarkRP. I'll test this again with normal DarkRP weapons.
4. You should **not** remove people's shipments or weapons without their consent. Many people store shipments in their base for hours on end. Removing it after a given time will make those people **very** angry, and for good reasons too. *"Fucking DarkRP keeps deleting my shit"*. I'm not making this.
5. Decent idea, but it will be disabled by default.

**Comment by deinemudda32** [comment]
1. But would help, but okay :D.
2. if the sqlite database get's too big, it just keep not saving stuff, thats my experience, I have friends with worked a lot with SQLite and they say the same thing like I now do.
Data is just for keeping things safe, like logs, doorgroups or whatever important. I want to keep that stuff, and darkrp should just support it I think, Its a big mod and it should not exclude some things the owner doesn't like, sorry my opinion :/.
3. I use the M9K Weapons Pack, I know its really bad coded. But there isnt any alternate. Without FAS:2 Which I personally doesnt like.
4. Yea but a option would be good either. I know the kiddys which store this shit.
But a timer that goes 2 hours and delete himself on deletion of the shipment, would be a good suggestion just for the performance, people doesnt have to use it, noone has, but its just a suggestion.
5. ;) Of Course.

**Comment by HDG-MrDeeJay** [comment]
saving to data helps no one. SQLite is more reliable and more secure. If 
anything SQL fucked up, it would be MySQL because MySQL is retarded.

Clear out wallet info from time to time, delete wallets from players 
that haven't joined in a month. Don't ask me how to figure that one out, 
my job was to tell you how to reduce the size of your DB.

Don't you dare say there is no alternative to M9k. You can always make 
your own weapons, or rewrite DarkRP's guns. There is also Customizable 
Weaponry, Mad Cows, CS Realistic... do I really need to go on? Stop 
being lazy.

Removing shipments and crap from people is straight up a bad idea. To 
combat spamming them, shipments merge, and when destroyed, unlike DarkRP 
2.4.3, we get a single entity with a number of uses, as opposed to a 
mountain of entities. If you cannot, as a moderator, keep your server 
from being flooded with entities, then it may not just be the gamemode's 
fault.

Come to think of it, a lot of this suggestion sounds like they can be 
made with darkrp modules.

**Comment by deinemudda32** [comment]
Just another hate post however. 
I try to answer without any offenses, as I respect youre opinion also.

1. "Clear out wallet info from time to time, delete wallets from players that haven't joined in a month. Don't ask me how to figure that one out,"
Thank you. Did you expect I recode every SQL Save DarkRP has completly or what?
When the mod themself doesn't support that, why should I?
Data is not that unstable, just for saving some shit is useful.
It could be exploited but some people might wanna use it. Like me.
You code everything new for me if you have the time. Else youre lazy ;).

2. There are 2 public weapon packs which are popular and working.
Custom Weaponry is in my opinion nothing for DarkRP.
Mad Cows is a error thrower and alot is not working.
CS Realistic, just a reskin of the standard CSS Weapons.
I'm not lazy for not counting every ****** weapon pack, sorry dude. Your'e totally wrong.

3. Removing Shipments isn't that bad idea, It sounds like one but isn't actually.
If you have a server with maybe 64 people everyone spawns 100 shipments and they stay forever.
Results in a crash mostly. 
"If you cannot, as a moderator, keep your server from being flooded with entities, then it may not just be the gamemode's fault."
It isn't my fault and it isn't the fault of the gamemode as moderator its just not my job to fucking do everything that comes in my way. Why does Sandbox has a entity/prop or what ever limit?
I don't even know if DarkRP has an entity limit. I think there is only one for vehicles, ya know what I try to explain.
Don't begin with buy a new server, I have very good hardware, If you'd like to know feel free to pm me.

4.I didn't wrote the suggestions text to get this for me, I do have the most of this already, but I just wanted to help out a little bit with good suggestion to probably help DarkRP and of course the users of it.

5. Your'e comment is completly useless and I won't answer again to such hater comments, just think before you write. You think really I just wrote this fucking large text to become 2-3 scripts without work, I suggest not difficult stuff right here, I could do it my own either, I just want it to become a part of DarkRP either, but people who think I want something bad could not understand that, right hm?

Please just respect my text and my person and don't write such things again!

Sorry If my text sounds offensive, It really shouldn't sound like this. :)

**Comment by FPtje** [comment]
I am amazed by how easily you take offense. I'm having none of it. I'd
agree if he did nothing but call you names, but he didn't and even gave you
good arguments for his opinion.
Whereas you tell him to stop posting, I ask him to continue if he so
pleases. This is an open discussion platform.

**Comment by HDG-MrDeeJay** [comment]
Indeed

**Comment by deinemudda32** [comment]
"Come to think of it, a lot of this suggestion sounds like they can be made with darkrp modules."
"Don't you dare say there is no alternative to M9k."

For me this sounds very offensive. However if it wasn't meant so, then I'm sorry ;)

**Comment by HDG-MrDeeJay** [comment]
It was only meant as personal opinions and emphasis, respectively.

When I said "Don't you dare say there is no alternative to M9k." it was 
because that I was slightly offended that you straight up mentioned M9k 
or FA:S and, without looking directly at the post now, it sounded as if 
you assumed those were your only options.

I will admit though, Mad Cows is broken because the guy who took control 
of it (Nyan cat i think his name was) is less skilled at LUA than a 12 
year old with a brain injury. I've fixed it myself and given him the 
fixes about 8 times, and each time he reverts them and wonders why they 
are broken, because I have to work around his shitty scripting and now 
i've just realized im ranting so ill stop.

And i honestly think that most of these suggestions can be resolved with 
custom darkrp modules, community made. Most of the plausable ones. I 
know the decay option can be done as a module, although I'm not sure if 
any purchase hooks that DarkRP presents included the resulting entity, 
let alone children of those entities (Such as weapons spawned from 
shipments, etc) which would lead me to suggest not relying on purchased 
entities as a whole, and just detect whitelisted entities and supply 
some timers to delay their removal. Hell screw the timers and work with 
a think hook and CurTime(), like how DarkRP (used to?) handle jail 
timers display.

**Comment by deinemudda32** [comment]
I know it can be done with modules ;). Therefore is disabled_defaults.lua.
I just wanted to SUGGEST it, I don't want help from you getting it done :D .
I only think its good to have it built in DarkRP.

I didn't look in jailtimers so, and just used CurTime() in weapons.
Even I rarely used think hooks.
So I just say nothing about that.

Greetings.

**Comment by HDG-MrDeeJay** [comment]
That last word is mistranslated, it gave you a synonym for hello. Just 
thought you may want to know that. If you are using google translate, 
that would be because Google has issues detecting nouns, verbs, 
adjectives, and more. Its better to translate one word at a time, you 
can be far more accurate.

Back on topic, you may want to look into those things man, DarkRP is a 
treasure trove of cool coding tricks. I learned how to filter default 
functions from DarkRP and learned how to make live, viewable timers like 
in the Jail shit.

And while I'm not saying your suggestions are bad (except some), I am 
saying that a lot of them sound like they are server specific, as in 
only one or two servers would use them. It would be like rewriting a 
section of DarkRP just so that one particular map was compatible. To 
hell with that, theres no point forcing, what, a good 250,000 DarkRP 
server's to update their game files for one thing they would never need 
to use. I think this same reasoning, along with "Whenever someone edits 
a core file, an issue is posted on GitHub complaining about something 
not working because a core file was edited" applies to the creation of 
the darkrpmodification system.

But I digress.

**Comment by deinemudda32** [comment]
I don't use google translate :D.

Every server has different preferences and if there is a feature for ent decay then alot of servers will use it, I'm sure of that.
And if not it wouldn't be the only DarkRP function which no pig uses.
There still alot which arent used too.
Youre argument isn't that strong therefore.
But if you dislike it, its ok :) I don't, okay in some points too but not in all.

**Comment by FPtje** [comment]
I just tested the third thing and it works fine with DarkRP weapons.
