### ISSUE TITLE
The "/" won't work.

### ISSUE THREAD

**Issue by OgeGhost** [FPtje/DarkRP#1778]
I finally narrowed it down from chat tags to this. At first I thought chats tags was making //ooc not work /advert etc. but I realized all "/" commands don't work 
ex: /warrant, /want, /drop 
"It's not the game mode, since i replaced it a lot of times"

**Comment by FPtje** [comment]
Are you dead while trying? Because I recently added on option where chat commands don't work if you're dead. Set `GAMEMODE.Config.deadtalk                      = true` to disable that. I just tested it myself and it works.
![2015-02-12_10-37-42](https://cloud.githubusercontent.com/assets/1202014/6164835/38c69e94-b2a3-11e4-997d-ba253b5d7989.png)

**Comment by OgeGhost** [comment]
@FPtje  no command works at all that uses / like lets say /drop | /want none of it works dead or alive / wont work in game

**Comment by FPtje** [comment]
This is not a help forum.

**Comment by HDG-MrDeeJay** [comment]
And in case you need help finding it, the help forum can be located at 
http://forum.darkrp.com/
