### ISSUE TITLE
[Suggestion] Permanent Job Ban

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#1779]
Everyone knows this. Loads of kids on DarkRP Servers who are simply not able to play as a CP, but are still enjoyfull players in general.

If Admins now ban them from their Job, they can switch back as soon as the server restarts/crashes or even the map changes.

How about adding a permanent Job Ban? It should last till another admin revokes this ban - without a need to care about reconnets/restarts or map changes.

**Comment by HDG-MrDeeJay** [comment]
The issue with this is that (if memory serves me) the only way you can 
index the jobs for data storage would be via the team number, which 
would change every time you add a job...

unless you add jobs correctly and put new ones at the bottom, and not 
wherever you fucking please. The amount of "coders" that do that shits 
me up the wall.

**Comment by Neosinos** [comment]
I dont really think this would be a huge Issue, honestly. Since its the
server owners fault if this happens - and even when it does happen, its
still no big deal.

Am Donnerstag, 12. Februar 2015 schrieb Nathan Davies-Lee :

**Comment by FPtje** [comment]
Currently you can do this in a primitive way by editing the customcheck of jobs. The thing is that the current job ban does its thing well and may people like it the way it is (i.e. temporary). I can't remove that.  Having both coexist is confusing.

This can be made using this hook:
http://wiki.darkrp.com/index.php/Hooks/server/playercanchangeteam

I'm deciding to leave it to diy.

**Comment by Neosinos** [comment]
The thing is just this is something which admins should be able to do on
the fly. With hundreds of players owners cba to add and remove the players
manually.

Coexisting shouldnt be a problem. After the last button you'd just add this
new 'permanent' one, and users can decide themselves what to pick.

Am Donnerstag, 12. Februar 2015 schrieb Falco Peijnenburg :

**Comment by Bo98** [comment]
> With hundreds of players owners cba to add and remove the players manually.

You could use the MySQLite library.

**Comment by HDG-MrDeeJay** [comment]
Yes but that would imply that server owners understand LUA, or have a 
'coder'. What with Coderhire / ScriptKiddie or whatever site it is now, 
kids just fork over money to people who make shitty addons like that one 
vote menu for TTT that removes EVERY fucking hud hook just so that it 
can localize them and break shit if anyone tries to open chat.

But i digress. My point is that owners will just throw their money at 
coderhire, and unfortunately nothing on coderhire or whatever its 
replacement is has anything good because all the coders care about there 
is a quick buck.
