### ISSUE TITLE
My admins and I can't noclip!

### ISSUE THREAD

**Issue by thelonlypanda1** [FPtje/DarkRP#1786]
On my DarkRP server my admins and I can't noclip (by pressing v). Can someone give me a detailed instruction on how to fix this please?

**Comment by Neosinos** [comment]
This is not a help forum. Please go to http://forum.darkrp.com - people there are able to help you. And if you do not want to get blamed again, be sure to Close your "Issue" Ticket yourself.

**Comment by thelonlypanda1** [comment]
I have seen plenty of people asking and receiving help on here so stfu you douchebag.

**Comment by thelonlypanda1** [comment]
Btw I fixed it myself.

**Comment by Neosinos** [comment]
You do realise spamming everyone with the Reopening will get you banned here? I'm not being a douche here, I just told you where you're able to find help for your Issue.

**Comment by thelonlypanda1** [comment]
this is my thread so really im spamming myself.

**Comment by thelonlypanda1** [comment]
and i was doing it for fun

**Comment by Neosinos** [comment]
And everyone else contributed to it.
My gosh. @FPtje ...

**Comment by thelonlypanda1** [comment]
nobody contributed but me and you

**Comment by HDG-MrDeeJay** [comment]
You know, every time you fucking clicked Close/Reopen, I received a new 
fucking email. 20. Fucking. Emails. You can kindly fuck off, because I 
made a pull request saying to get help from forum.darkrp.com, Falco 
always tells people like you to goto forum.darkrp.com, I'm like the only 
one aside from Bo98 who really gives help to people who ask for it on 
github, and I'm stopping that.

inb4 blocked out of the github by falco.

**Comment by FPtje** [comment]
God damn would you look at this spam
