### ISSUE TITLE
[Issue] DarkRP Modification with 2.6.0

### ISSUE THREAD

**Issue by SpeedoSausage** [FPtje/DarkRP#1794]
After a simple update to DarkRP 2.6.0, I found that most addons needed to be updated(Understandable), yet why does it seem DarkRP modification addon is experiencing issues as well? I looked into it and saw that DarkRP Modification should transition fine, but didn't. Maybe this is an issue others are having, maybe not. The jobs folder is not recognizing the "GAMEMODE.DefaultTeam" and corrupting random jobs. I'm not sure if this may be an issues others are having(I have a friend who is having the same issue) but I cannot find a solution.

![ss 2015-02-19 at 04 30 00](https://cloud.githubusercontent.com/assets/11074736/6266964/99e35a7c-b7f4-11e4-9f04-dd21c36fc23a.png)

**Comment by Neosinos** [comment]
As far as I can see through those Errors its clearly a Issue of the Law
Enforcment Job, there is a Corrupt or not existing Model in your jobs.lua
on Line 458 - this issue can not be caused by DarkRP 2.6 since nothing
changed which could have affected this, thats your configuration issue. Try
removing darkrpmodification (or replacing with default) and you'll see it's
working again like with every other DarkRP Server too.

Also, this is not a help forum. So please post this under
http://forum.darkrp.com - people can help you there, Github is only for
actual Bugs.

2015-02-19 14:04 GMT+01:00 SpeedoSausage <notifications@github.com>:

**Comment by FPtje** [comment]
I'm more and more doubting whether that "model exists" check in Gmod really
works. This issue needs more investigation. Can you email me your custom
jobs and the addons the models come from?

**Comment by Bo98** [comment]
The GAMEMODE.DefaultTeam error may be because of the previous errors. I believe corrupt jobs now break execution but I haven't checked.

**Comment by FPtje** [comment]
Good point.

**Comment by FPtje** [comment]
Shouldn't the call to error halt the execution though? Doesn't it stop that DarkRP loaded hook from being reached?

**Comment by SpeedoSausage** [comment]
Neosinos, As I wanted help, I began to question the majority of the issue itself so brought it to attention here as it is a brand new update and has happened to my friend as well.
FPtje, I will email you my jobs file.

**Comment by Bo98** [comment]
The DefaultTeam check is done in InitPostEntity.

**Comment by FPtje** [comment]
Huh that should have been in that loaded hook.

**Comment by FPtje** [comment]
Alright, I got the email with the jobs. I've fixed some minor simplerr problems related to this issue (there's a nested error in that screenshot and the DefaultTeam error shouldn't have been showing up).

However, the main problem seems to be this:
One of the jobs used player models from this addon:
http://steamcommunity.com/sharedfiles/filedetails/?id=121961644

That's also where the error comes from. I looked into the issue and found the following:
- If you subscribe to this addon and start GMod, the addon **works**. It downloads, it mounts and everything works.
- If you put this addon in a collection with which you start your dedicated server, you get an error. This error happens *every* time you try. It's 100% reproducable.

The error:

```
Mounting Addon 'NYPD 1940's Model-Group' (121961644)
Downloading...
  100%
Done!
Extracting...
Not loading addon 'addons/ds_121961644.gma' - addon header invalid
Couldn't mount addon [NYPD 1940's Model-Group][addons/ds_121961644.gma]
Removing bad addon addons/ds_121961644.gma
```

Now I managed to catch `ds_121961644.gma` before it was removed. It was a <1KB file with this as contents:
```
HTML><HEAD>
<Fô
Q
```
Something **definitely** went wrong with downloading here. GMA files do **not** start with HTML tags. The properly downloaded GMA (from normal gmod) shows the following metadata:
```
crc                   = None
Magic value           = None
format version        = '\x03'
Steam ID              = 76561197997313414
Time created          = 2013-01-31 23:46:30
required content      = ""
addon name            = "NYPD 1940's Model-Group"
addon description     = "[h1]Ready for Duty, Officer?[/h1]

A modelgroup containing default males (01-09) dressed as New York Police Officers in the 1940's.

Inspired by Mafia II's Police Officers.



[h1]Features:[/h1]

[list]

 [*] Fully posable Ragdolls

 [*] Can be used for NPCs (and player models; still checking that!)

 [*] Great for Roleplay Communities and posers!

[/list]



[h1]Changelog:[/h1]

[list]

 [*] 27.01.2013 - Added NPC spawnlist for the Models!

 [*] 31.01.2013 - Added playermodels!

[/list]



[h1]Credit[/h1]

If you use them for poses, roleplay or any other things I'd be happy if you would show me your work with them and credit me!"
addon author          = "author"
addon version         = 1

Files: <lots of files here>
```

-------------------

# Conclusion:
The errors are most likely caused by a bug in the gmod dedicated server. Specifically, it is **UNABLE ** to download this specific addon. Here's what you can do as a workaround: 
- Subscribe to the addon 
- Start GMod, make it download the gma
- Move `nypd_1940s_model-group_121961644.gma` to the `addons/` directory of your dedicated server
- Rename `nypd_1940s_model-group_121961644.gma` to `ds_121961644.gma` on the dedicated server. Note that `121961644` here is the workshop id of this addon.


This addon is probably not the only addon with which this can happen. Check the **server** console for messages like the one shown on top of this post. When you see such errors, you can execute the steps of the conclusion to temporarily work around the issue. 

GMod devs have been notified of this issue.

**Comment by FPtje** [comment]
Also, if the error about incorrect models happens even with correctly downloaded addons, please feel free to post/email me more info. I will look into it further.
