### ISSUE TITLE
DarkRP ---> ULX crashing issue.

### ISSUE THREAD

**Issue by JohnAtPG** [FPtje/DarkRP#1814]
I was told this issue is from DarkRP which is why I am reporting this here. I had a coder make something for me and as part of that job - he was testing the ULX kick feature on himself in his DarkRP server and mine - both running DarkRP 2.6.0

If you use the chat command to kick (!kick) on yourself - the server will crash. He said he knows your email Falco - and would report this to you but I figure I might as well post it just in-case he forgets.

He said something about DarkRP trying to find your name to print to chat but you're gone already so you don't exist - therefore server crashes? Kicking yourself with console or the ulx menu works fine.

**Comment by HDG-MrDeeJay** [comment]
Actually, this isn't a bug in DarkRP. I found this myself in ULX, it 
attempts to refer to a player after the player has left, causing it to 
flip out. While it never crashed when used in TTT, a similar sounding 
bug occured when trying to kick or ban players, and ULX would fall back 
to printing (CONSOLE) instead of the player name.

TL:DR Its not specifically related to DarkRP, as I have replicated a 
similar, if not identical bug on TTT. ULX needs to be updated (although 
I don't know why, it just randomly started happening despite no update 
being made to ULX)

**Comment by JohnAtPG** [comment]
Well it only started happening once I put DarkRP 2.6.0 on my server. This coder told me it was specifically caused by DarkRP cause of a Player:IsValid() check not being ran but I suppose the same could go for ULX.

All I know is everything was fine until 2.6.0 was added so there must be some change there that's doing it cause I'm able to kick myself with ULX via chat command on DarkRP 2.5.1 and no server crash or anything.

**Comment by HDG-MrDeeJay** [comment]
Hmm. Prior to 2.6, if you were to kick or ban a player, would ULX say 
"<admin> kicked (Console) for reason: <reason>" or "<admin> kicked 
<player> for reason: <reason>"? If so, your crash could be the sum of 
two problems, one of which could lie within DarkRP, the other in ULX.

**Comment by TheEMP** [comment]
Are you running the latest version of ULX? I belive they fixed this issue several months ago, as seen in this pull request https://github.com/Nayruden/Ulysses/commit/cb18e356c83798faeebca22eb433f464e7af992b

**Comment by FPtje** [comment]
Thanks @TheEMP
