### ISSUE TITLE
Randomly getting disconnected from server

### ISSUE THREAD

**Issue by MrGeekabir** [FPtje/DarkRP#1837]
I am getting this error randomly while on the server and getting disconnected.

Player [DPAE] MrGeekabit has left the server.
Dropped [DPAE] MrGeekabit from server ([DPAE] MrGeekabit timed out)

**Comment by HDG-MrDeeJay** [comment]
Is this your server? And if so, how is your connectivity to this server?

Without any errors, all that can be said from this is that you are 
simply losing connection to the server. You may find that the community 
may be able to help you out more. Try asking at http://forum.darkrp.com/

**Comment by MrGeekabir** [comment]
I have really great connection... Also, this also crashes my gmod so... yeah

**Comment by MrGeekabir** [comment]
http://pastebin.com/M5tXwvUt

**Comment by HDG-MrDeeJay** [comment]
Unless Falco has some mystical lua_run code that will shed anything on 
this, all I can suggest is launch your server with the startup argument: 
"-insecure"

This will mean your server will not request VAC authentication or shit. 
It doesn't matter anyway, because Garry's Mod is not affected by VAC to 
any extent I am aware of, and -insecure doesn't disable Garry's 
Anti-Cheat (although that isn't in operation atm). I remember 2 years 
ago there were a large set of issues with servers running in VAC Secure 
mode, where players would randomly "time out" with error code 5. It's 
not exactly the same as seen in that pastebin, but its the closest fix I 
can give.
