### ISSUE TITLE
Health HUD doesn't use MaxHealth

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1915]
Line 83 of modules/hud/cl_hud.lua:

		local startingHealth = GAMEMODE.Config.startinghealth

**Comment by HDG-MrDeeJay** [comment]
because MaxHealth isn't used by the gamemode therefor we dont need to calculate it?

**Comment by Partixel** [comment]
Some jobs may want a custom max health?

**Comment by HDG-MrDeeJay** [comment]
Well then thats a modification that the job's creator will need to implement themselves. Easily done with their own health hud (Which of course is easy to make), and adjusting the MaxHealth on a successful job change to X job.

IMO its not something needed in the vanilla gamemode. Unless you intend to have op custom jobs that have all the weapons and spawn with 200% hp, which is utterly stupid and if you use that as a reason for having it, I think you will find I wont be the only one laughing

**Comment by Partixel** [comment]
> Midget, small guy, has lower health

It's not exactly a large change to fix this, and it's not calculating anything, surely it would just be getting a value?

**Comment by HDG-MrDeeJay** [comment]
Even so, I seem to recall something about the hud not getting redesigned or new features other than patches and performance tweaking, something about retaining the old design.

And like I said before, it takes no effort at all to simply modify the HP bar yourself, all the core code is presented in an example mod in the darkrpmodification. Then instruct the server to respawn on job change (most servers do this already to enforce OnPlayerSpawn functions and to combat job abuse), and use the appropriate argument to adjust the players max health on spawn.

I don't see why its needed in vanilla. Vanilla jobs have no need for MaxHealth, as the integer is easily converted to a percentage with no effort, and jobs such as midget can be manually RP'd as a citizen by using /job Midget, and pretending you are a midgjet.

![Use your Imagination || Image of Sponegbob ||](http://cdn.meme.am/instances/58687479.jpg)

**Comment by Partixel** [comment]
The problem is, this was requested for my addon, and I can't exactly force every user to use a custom hud just for maxhealth to work.

Also, 8/8 would use imagination again.

**Comment by HDG-MrDeeJay** [comment]
Ok, so lets say it was implemented into DarkRP vanilla.

Now you have a single vanilla hud that supports MaxHealth.

Mind you, a lot of the custom huds I've seen on Coderhire, Scriptfodder, and even the workshop don't use MaxHeatlh. And what is the first thing most modern DarkRP server owners do? Download as many mods as they can to replace the UI, from the HUD to everything Derma. Rendering your proposed update pointless until the jewish opportunists that kill the community get off their mountains of sheckles and include MaxHealth into their scoreboards, Huds, etc.

Look, While MaxHealth is a cool function with many possibilities, unless it was there from the early days, there is little chance it will make a difference now.

(Willing to also put money on very few servers ever using such a feature if it were supported in vanilla)

**Comment by Partixel** [comment]
I cri everi tim.

We'll see what FPtje says on this matter. :P.

**Comment by HDG-MrDeeJay** [comment]
Yes, we shall.

**Comment by Partixel** [comment]
I know it would go unused by the majority of the community, but does it not make more sense to have a health gui basing it's percentage off of health / maxhealth instead of the health that a player is assumed to start with?

**Comment by Partixel** [comment]
Thanks FPtje <3

**Comment by FPtje** [comment]
This is a perfectly reasonable request, and one that makes perfect sense as well.

`GM.Config.startinghealth` should simply have the behaviour of setting the maximum health of a player. It makes little sense to have a player start with a certain amount of health, only to make it impossible to regain that health when hurt. This was the case before the commit above. That's why the medkit was also changed to reflect this.

Changing the maximum health of players depending on jobs is a very good RP mechanic. I remember Arizard mentioning this in a thread about how RP can be improved. You could make thieves weaker than, say, gundealers to make breaking in a risky operation. This mechanic also exists in a more complicated form in Warframe, where different "frames" (characters) have different maximum Healths (and shield and armor). This helps in preventing certain characters from being overpowered and others being underpowered.

This changes **nothing** in the design of DarkRP. Under the default settings the HUD and the medkit behave exactly the same. When you change the starting health, or when you set a player's max health in a job or addon, the HUD and medkit will be compatible. This means that players with a max health of 300 will have **half** their health bars filled when their health is 150. The medkit can heal them back up to 300. That's because 300 is their maximum health, and 100 isn't anymore.

It makes perfect sense.
