### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1935]
Every end of the script, you all leave a blank line, I never understood why.
It seems pretty useless.

**Comment by HDG-MrDeeJay** [comment]
Not a bug. Doesn't require any changing.

Thats something you ask on the forums.

**Comment by deinemudda32** [comment]
Oh its a huge issue.
My server loads 0.0000000000000000000000000000000000000000000001 miliseconds slower.
I never can sleep again!

**Comment by HDG-MrDeeJay** [comment]
i can help you get to sleep.

Tell me, do you like fish?

**Comment by deinemudda32** [comment]
yea fishsticks, Im a gay fish..

**Comment by HDG-MrDeeJay** [comment]
I know a great place where you can sleep with them.

  WikiMiniAtlas
11°22.4′N142°35.5′E 
<http://tools.wmflabs.org/geohack/geohack.php?pagename=Challenger_Deep&params=11_22.4_N_142_35.5_E_>

**Comment by deinemudda32** [comment]
Thank you!

**Comment by Bo98** [comment]
It's a convention. I believe it originated from C but has been followed through Unix history. Technically speaking a line in a text file is a "sequence of zero or more non-<newline> characters plus a terminating <newline> character". Some Unix tools expect this behaviour and have side effects otherwise.

It matters less for Lua files, but is still a widely followed standard.
