### ISSUE TITLE
Questions regarding warrant system

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#1987]
Why are cops not able to issue a warrant on a dead criminal?
If you are forced to kill them, how does it make sense to not allow a warrant in order to continue house search.

Why are cops not able to issue a warrant on an arrested criminal?
If you reach the owner of the house quickly and arrest them, you can no longer issue a warrant because they are in jail. How does this make sense?

**Comment by FPtje** [comment]
> Why are cops not able to issue a warrant on a dead criminal?
> If you are forced to kill them, how does it make sense to not allow a warrant in order to continue house search.

The original idea was that you cannot issue a warrant for a dead person because there is no use to get evidence for arresting a dead person. The thing is, if someone has printers behind a door, and you kill the person before you get to the printers, the printers stay. The player can return to them when he respawns. When you allow the warrant to stay on a dead player and/or allow a warrant to be obtained for a dead player, the question is when it becomes invalid. On respawn or on a timer? I'd go for a timer.

> If you reach the owner of the house quickly and arrest them, you can no longer issue a warrant because they are in jail. How does this make sense?

After someone is arrested, you can search their house and get rid of their printers and illegal stuff. That's a good point. I worry, though, that allowing this might open up room for abuse. People complaining about getting arrested so that cops can search their homes without challenge. Cops will be more likely to arrest people sooner, which is a bad thing. Getting arrested is already a punishment, making it even more punishing isn't a good idea.

**Comment by MStruntze** [comment]
I understand your points.
About the warrants on dead people. Let's say the cops starts a raid on some base. People like to build huge bases which oftens makes it hard to get near them. The only option is to shoot through everything. Let's say the owner of the base gets killed and just stays dead. Now when the current warrant expires, the cops have no way to enter the base to kill the rest of the guys? I can understand that this could be abused  as you point out, but I really think there should be made some changes.
When a criminal is arrested, you can no longer use your warrant (pretty sure) or at least your can't issue a new one. Let's say you've infiltrated a base and arrested the owner. The raid was successful. The issue though is that you can't get out of there, because the entrance is made of fading doors, and you'll need a warrant for that. Again the cops will either have to kill themselves og wait for the guy to get unarrested.
I can see that while writing this, there are many ways it can be abused, which I hadn't really though of before. Maybe there are alternative ways, I don't know.

**Comment by FPtje** [comment]
Good point.
