### ISSUE TITLE
removePocketItem and dropPocketItem Functions Don't Seem To Work

### ISSUE THREAD

**Issue by Triage757** [FPtje/DarkRP#2006]
Right, so these do not seem to work. When I run them I just get this error:
http://pastebin.com/TgdK9QCn

The code I'm using. I have also tried removePocketItem and it still doesn't work. I get the exact same error.
http://pastebin.com/Ye8JPTpP

I even run in console to print out what's in the pocket table and it returns the correct items with the correct entity names. 
http://pastebin.com/0UNUW1FA

And I still get that error above.

**Comment by FPtje** [comment]
Documentation error. item is supposed to be a number, with 1 being the first item in the pocket.

**Comment by Triage757** [comment]
Wait, then  how can you remove a specific entity?

**Comment by FPtje** [comment]
Using classnames would be ambiguous, imagine having **two** "durgz_cocaine" packages in your pocket. One being refined or something and the other one being raw (I know durgz_cocaine doesn't have this parameter, but for the sake of argument, let's assume it does). 

Telling the pocket to remove *"durgz_cocaine"* would be an ambiguous command. Should it remove the raw one, the refined one or both? That's why you give the number instead. Removing 1 will (in your case) remove that cocaine thing.

How would you remove a specific entity? Very simple

```lua
for k,v in pairs(ply:getPocketItems()) do
    if v.class == "durgz_cocaine" then ply:removePocketItem(k) end
end
```
Note that the above code removes ALL the durgz_cocaine items you have in your pocket. I't s up to you to decide what it removes. You can decide using getPocketItems.

**Comment by Triage757** [comment]
Thank you so much for clearing this up! I really appreciate it.
