### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by SirKlutch** [FPtje/DarkRP#2149]
Okay, what exactly was the point of changing the console commands to chat commands? Not a major issue but it's a bit annoying after all these years of the commands being ran through console you make chatCommands a thing. Please bring back the console commands or add both please.

**Comment by FPtje** [comment]
they are still console commands, they're just renamed. They were changed in favour of consistency and because it made it easier for me to integrate them with CAMI.

Instead of writing `rp_setmoney anus 999999999` in console, you now write `darkrp setmoney anus 999999999`. The chat command is a bonus.
