### ISSUE TITLE
Spectate: Suggestion

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2221]
If you spectate someone in First Person.
How about drawing the view model like in TTT or atleast remove the weapon world model.
Just looks awful ugly.

**Comment by HDG-MrDeeJay** [comment]
that spectate is rendered clientside, whereas ttt is rendered serverside.

I could be wrong, but I believe that is why that cant happen and its 
clientside so as to avoid cheaters noticing admins spectating, which so 
many cheats have spectator alerts.

**Comment by deinemudda32** [comment]
The world model of the weapon is still there, isnt there anyway it moves with the player model atleast.

I guess its because the SetNoDraw.
Maybe it could be replaced by coloring the player entity invisible or using a material.

**Comment by FPtje** [comment]
I can't do the viewmodel thing. The viewmodel entity of other players is not networked unless those players are being spectated trough Source. I'm not using Source's spectate because that notifies the players.

The best I could do is make a hacky approach, but it would have a high chance of messing up your view model when you get out of spectate.
