### ISSUE TITLE
Chat / Console Commands

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2268]
Could you add support for using '' instead of "".(for chat / console commands)

If I run a command in a clientside luafile via RunConsoleCommand it returns these strings ' ' instead of the needed " " ones.

Example:
RunConsoleCommand("darkrp", "check".." /"player"/".." 25") returns darkrp check 'player' 25 which is not possible to run.

**Comment by BillyOnWiiUIn144p** [comment]
Learn to escape http://www.lua.org/pil/2.4.html

**Comment by FPtje** [comment]
this is bullshit.

**Comment by deinemudda32** [comment]
Console automatically converts "double quotes" to "single quotes".

**Comment by BillyOnWiiUIn144p** [comment]
How is that anything to do with DarkRP?

**Comment by FPtje** [comment]
use userids.

**Comment by deinemudda32** [comment]
DarkRP doesnt support single quotes in commands.

UserIDs?
https://wiki.garrysmod.com/page/Player/UserID
I dont think these are supported.

**Comment by Bo98** [comment]
DarkRP supports UserIDs:

https://github.com/FPtje/DarkRP/blob/e19e0066dc666f20327945f2f4392436f1807006/gamemode/modules/base/sh_util.lua#L61-L63

It also uses it internally because running concommands by player name is not as reliable:

https://github.com/FPtje/DarkRP/blob/85bc519c311e96aba500dd17ac74df275741ad78/gamemode/modules/fadmin/cl_fadmin_darkrp.lua#L38

**Comment by deinemudda32** [comment]
I use userids now, thanks :).
