### ISSUE TITLE
Two issues with CAMI.RegisterUsergroup in DarkRP

### ISSUE THREAD

**Issue by Nayruden** [FPtje/DarkRP#2276]
Given the default ULX usergroup structure, if I run the following...

```lua
CAMI.RegisterUsergroup({Name="admin2",Inherits="operator"}, "ULX")
```

DarkRP immediately executes...

```lua
CAMI.RegisterUsergroup({Name="admin2",Inherits="user"}, "FAdmin")
```

First problem: Why is register being called again?
Second problem: Why does DarkRP think it's inheriting from user?

I verified that "operator" is registered in CAMI and shows up in CAMI.GetUsergroups().

As a sidebar, what's with 'noaccess'? I've had a few users ask about it.

**Comment by FPtje** [comment]
FAdmin shouldn't immediately call RegisterUserGroup. That's fixed now.

It does send a message to the client which might call registerUsergroup if it finds the group doesn't exist yet.

The inheritance user is because in FAdmin usergroups can only inherit from user, admin or superadmin. It looks at the inheritance root and uses that to inherit from.
