### ISSUE TITLE
MySQL + MySQL not connected (before tick function starts) + Adding bot = Pain

### ISSUE THREAD

**Issue by MrBrax** [FPtje/DarkRP#2294]
I do this to start all the stuff before players get on; adding a bot to call initpostentity, start tick and timers.
First thing happens on this part: 
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/fadmin/fadmin/access/sv_init.lua#L313
before it all goes to shit.

**Comment by 00875** [comment]
MySQLOO runs on Think, so it does not connects to MySQL before player is connected. Thats why errors are happening

**Comment by MrBrax** [comment]
@00875 I know, maybe a check in mysqlite if it's connected?
`[ERROR] gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:286: attempt to index global 'databaseObject' (a nil value)`
is the general error

**Comment by 00875** [comment]
You can try tmysql4, it runs on Tick. Also, MySQLite should queue queries before connecting to DB.

**Comment by MrBrax** [comment]
@00875 I am using tmysql4, and it does not start until initpostentity is ran (tick/think start). The whole server is basically useless and unprepared before it.

**Comment by FPtje** [comment]
The error was reproduced on a local dedicated server by spawning a bot. The connection to MySQL was made in a 1 second timer, the bot spawns before the connection is made. That's something that doesn't happen with players. 

There was no comment as to why the connection was in a 1 second timer. Let's hope the connection doesn't time out and cause trouble when the time between server startup and the first player is long.

**Comment by MrBrax** [comment]
MySQLite.databaseObject could be checked if it's nil when doing a query..

**Comment by FPtje** [comment]
I tested it and this solves your issue.

**Comment by MrBrax** [comment]
Yeah it does, thanks. Was just a nod to 
>Let's hope the connection doesn't time out and cause trouble when the time between server startup and the first player is long.

**Comment by FPtje** [comment]
There are mechanisms in place to reconnect, specifically with mysqloo.
Adding a null check would cause bugs in that system to go undetected

**Comment by MrBrax** [comment]
Checking if the db object is nil? That wouldn't break anything, since you can't access/call it anyway.
I'd say it's general practice to check if something exists before calling something on it.

**Comment by FPtje** [comment]
You don't understand my reasoning. Have it in steps:

- server loses connection
- query is run
- through some bug, MySQLite doesn't reconnect, which it should

Now, without check:

- an error is thrown
- that error is reported
- I fix the bug that caused MySQLite to fail to reconnect

With the nil check:

- the query fails silently
- no one knows anything is wrong
- it seems everything is working fine, but in the meantime shit doesn't get
stored in the database
- I get vague bug reports about shit not being saved in the database and I
don't even know where to start looking for a cause, how to reproduce it or
how to do anything about it in general. The server owners that have the bug
are clueless about when the issue occurs, because they generally find out
that shit wasn't saved when the server restarts.

Seriously, preventing errors from occurring is not always the best
strategy. Null/nil checks can make your system undebuggable if you're not
careful.

**Comment by MrBrax** [comment]
Of course it would do an error when it's nil, but not exit the call stack, breaking everything in that hook.

**Comment by FPtje** [comment]
Nil errors always exit call stacks unless explicitly caught. What specific hook are you talking about? The FAdmin one? Yeah that gets fucked when an error occurs, shit generally gets fucked when errors occur, that's why we should make sure there are no bugs from which errors can be thrown. My whole point is that nil checks are not the right way of doing that.

**Comment by MrBrax** [comment]
The whole PlayerInitialSpawn breaks, not running any future hooks in that call. Sure it works now, but in that case that it wouldn't connect.

**Comment by MrBrax** [comment]
![Error](http://rp.braxnet.org/scr/145302265580965.png)

So here's something fun.

**Comment by Bo98** [comment]
What's that got to do with the DB?

**Comment by MrBrax** [comment]
@Bo98 related to the adding of players before everything is loaded, i guess. But i'll probably just modify them myself.
