### ISSUE TITLE
Pocketed Items Lua Error

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2301]
```
lua/includes/extensions/entity.lua:396: attempt to call a nil value
  1. RestoreNetworkVars - lua/includes/extensions/entity.lua:396
   2. Load - lua/includes/modules/duplicator.lua:286
    3. DoGeneric - lua/includes/modules/duplicator.lua:942
     4. deserialize - gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:155
      5. dropPocketItem - gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:228
       6. dropAllPocketItems - gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:181
        7. fn - gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:309
         8. unknown - lua/ulib/shared/hook.lua:110
```
This Lua error pops up in Server Console now and again. Unfortunately I've not been able to reproduce it or see the events of what other player's are doing at the time the error occurs, so cannot provide any further details I'm afraid.

**Comment by FPtje** [comment]
It's when you drop a specific pocket item. You can probably reproduce it by spawning every custom entity you have on your server, pocket it and then drop it. One of them will surely give the error.

The pocket uses the duplicator system to store and then spawn entities. Entities that are incompatible with duplicator will throw this error. Put that entity in the blacklist and/or report to the author.

Also, if you find out, post here. I'm curious as to which entity it is.

**Comment by Hazbelll** [comment]
Thanks for the info. I'll post back if I find out what's causing it exactly.

**Comment by Hazbelll** [comment]
@FPtje I found the culprit. It's [FA:S 2](http://steamcommunity.com/sharedfiles/filedetails/?id=180507408).

When pocketing and dropping an FA:S 2 SWEP manually by the player, it will not error, however the dropped SWEP becomes "ghosted" (players can see it in the world, but cannot interact with it by any means, including physgun, toolgun, context menu, map cleanup etc.).

However, if a player is forced to drop their entire inventory of pocketed items (such as by dying or being arrested with both `GM.Config.droppocketdeath` and `GM.Config.droppocketarrest` respectively), it will error. The SWEP shall remain in the player's inventory, but will behave oddly. Dropping the SWEP will either cause it to become "ghosted", or it'll just vanish entirely. The GUI of the pocketed items will act a little odd too. In the event that all of a player's items were dropped from their pocket on being arrested with an FA:S 2 SWEP pocketed and `GM.Config.teletojail` enabled, the player will not actually be sent to jail.

**Simple Steps to reproduce:**
1. Drop an FA:S 2 weapon from a shipment (or spawn one into the world with the toolgun).
2. Pocket the dropped weapon (don't equip it into your loadout).
3. With the weapon in your pocket, you simply need to have your entire pocket emptied by some means, such as via the config variables above. The pocket will then error.

Easiest solution would be to disallow players from being able to pocket FA:S 2's SWEPs, but I'd like to request that perhaps we have an option to use the Pocketed Items Blacklist as a Whitelist instead? This can be much easier to maintain and is similar behaviour to how FPP works with its entity lists.

**Comment by FPtje** [comment]
I'll try it out and talk to spy about it.

**Comment by FPtje** [comment]
You can reproduce the issue with the duplicator tool. The author of the swep pack refuses to even look at it. There's nothing I can do.

> Never tell your password to anyone.
26 January 2016
20:11 - (FPtje) Falco: Is there anything in your FA:S 2 weapon pack that might break duplication?
20:13 - (FPtje) Falco: also, hi
20:13 - an inconspicuous terrorist: no idea
20:13 - an inconspicuous terrorist: actually
20:13 - an inconspicuous terrorist: fas 2.0
20:13 - an inconspicuous terrorist: are just weapons
20:13 - (FPtje) Falco: there's this issue on my DarkRP github
20:14 - an inconspicuous terrorist: so they shouldn' tbreak anything
20:13 - (FPtje) Falco: https://github.com/FPtje/DarkRP/issues/2301
20:14 - (FPtje) Falco: I'm still trying it out though
20:14 - an inconspicuous terrorist: no idea dude
20:15 - (FPtje) Falco: yeah
20:15 - (FPtje) Falco: spawn an ak-47, duplicate it
20:15 - (FPtje) Falco: [ERROR] lua/includes/extensions/entity.lua:396: attempt to call a nil value
  1. RestoreNetworkVars - lua/includes/extensions/entity.lua:396
   2. Load - lua/includes/modules/duplicator.lua:286
    3. DoGeneric - lua/includes/modules/duplicator.lua:942
     4. CreateEntityFromTable - lua/includes/modules/duplicator.lua:428
      5. unknown - lua/includes/modules/duplicator.lua:720
       6. ProtectedCall - [C]:-1
        7. Paste - lua/includes/modules/duplicator.lua:720
         8. LeftClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator.lua:61
          9. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:254

> 20:16 - (FPtje) Falco: it's interesting how none of the functions in the stack are FAS
20:16 - an inconspicuous terrorist: my thoughts exactly
20:16 - (FPtje) Falco: but it does happen only when duplicating your FAS weapons
20:16 - an inconspicuous terrorist: no clue why dude
20:17 - an inconspicuous terrorist: I have no dupe-related stuff in there
20:17 - an inconspicuous terrorist: tell him to use some other weapon pack
20:17 - (FPtje) Falco: no
20:17 - (FPtje) Falco: I can hear shit arguments
20:17 - (FPtje) Falco: but I won't relay them
20:17 - an inconspicuous terrorist: oh
20:17 - an inconspicuous terrorist: wut
20:17 - an inconspicuous terrorist: what do you mean?
20:17 - an inconspicuous terrorist: by 'shit arguments'
20:17 - (FPtje) Falco: how about you look into the issue?
20:18 - an inconspicuous terrorist: I don't want to go into old messy code lol
20:17 - (FPtje) Falco: instead of just telling the guy not to pocket your weapons/use a different weapon pack?
20:18 - an inconspicuous terrorist: if he doesn't like the weapons or they're causing an issue - switch to another weapon pack
20:18 - an inconspicuous terrorist: because clearly it's not working well within the context of darkrp?
20:18 - (FPtje) Falco: so you refuse to fix any issues?
20:18 - (FPtje) Falco: no it's not working in the context of sandbox
20:18 - an inconspicuous terrorist: way to jump to conclusions you fucking aspie
20:18 - (FPtje) Falco: 20:18 - an inconspicuous terrorist: if [...] they're causing an issue- switch to another weapon pack
20:19 - an inconspicuous terrorist: yeah
20:19 - an inconspicuous terrorist: do it
20:19 - an inconspicuous terrorist: obviously it's not working properly
20:19 - an inconspicuous terrorist: so just use something that works
20:19 - (FPtje) Falco: but what if it's a simple enough fix?
20:19 - an inconspicuous terrorist: well I don't know what the fucking fix lmao
20:19 - (FPtje) Falco: I mean we haven't even looked at how easy it is to fix, regardless of how shit the code is
20:19 - (FPtje) Falco: no I don't know either
20:19 - (FPtje) Falco: I haven't looked into it
20:19 - (FPtje) Falco: want me to spoonfeed that for you?
20:20 - an inconspicuous terrorist: want me to tell you to go fuck yourself, you passive aggressive autist?
20:20 - an inconspicuous terrorist: go fuck yourself
20:20 - an inconspicuous terrorist: I'm not obliged to fix shit for you, dumb fuck
20:20 - an inconspicuous terrorist: go be a fucking dick somewhere else
20:21 - (FPtje) Falco: you're not obliged to fix shit
20:21 - an inconspicuous terrorist: yeah, now either change your fucking tone or go fuck yourself
20:21 - (FPtje) Falco: but you can't expect me to tell Hazbelll to fuck off and use something else on your behalf
20:22 - an inconspicuous terrorist: why not?
20:22 - an inconspicuous terrorist: you didn't make the sweps
20:22 - an inconspicuous terrorist: so you have no control over them
20:22 - (FPtje) Falco: because it's your responsibility
20:22 - an inconspicuous terrorist: therefore tell him to switch if it does not function properly
20:22 - an inconspicuous terrorist: yeah, mine
20:22 - an inconspicuous terrorist: not yours
20:22 - an inconspicuous terrorist: AKA
20:22 - (FPtje) Falco: I won't tell them to go fuck themselves
20:22 - an inconspicuous terrorist: you tell him
20:22 - (FPtje) Falco: I can tell them that you're a cunt and that you refuse to fix it
20:22 - (FPtje) Falco: but I won't tell them to use something else instead
20:22 - (FPtje) Falco: also
20:22 - (FPtje) Falco: I'm not changing the tone
20:23 - an inconspicuous terrorist: then fuck off
20:22 - (FPtje) Falco: so to obey you I must now fuck myself
20:22 - an inconspicuous terrorist is now Offline.


The lad's always been difficult to work with. Even for me. Either way I can't help you.
