### ISSUE TITLE
c29058a causes addons to think that there are no PlayerSay hooks

### ISSUE THREAD

**Issue by 0tt** [FPtje/DarkRP#2310]
c29058a
```
hookremove      PlayerSay       ULXMeCheck
hookremove      PlayerSay       CAC.ChatCommands
hookremove      PlayerSay       Wire Text receiver PlayerSay
hookremove      PlayerSay       orgChat
hookremove      PlayerSay       Party Chat Command
hookremove      PlayerSay       REWARDS_PlayerSay
hookremove      PlayerSay       TitleChat
hookremove      PlayerSay       CarDealer::Modify
hookremove      PlayerSay       FoxedBot_PlayerSay
hookremove      PlayerSay       OpenAddonsPage
hookremove      PlayerSay       AWarn_ChatWarn
hookremove      PlayerSay       PlayXMediaQueryPlayerSay
hookremove      PlayerSay       maestro_hook

[ERROR] addons/maestro-master/lua/maestro/sh__hook.lua:37: yo dude what the fuck
  1. error - [C]:-1
   2. Remove - addons/maestro-master/lua/maestro/sh__hook.lua:37
    3. v - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:168
     4. unknown - lua/includes/modules/hook.lua:84
```
Maestro hooks aren't getting called:
```
maestro.hooks = {}
function maestro.hook(name, id, func)
    local n = hook.GetTable()[name]
    if not n or not n.maestro_hook or not maestro.hooks[name] then
        maestro.hooks[name] = {}
        hook.Add(name, "maestro_hook", function(...)
            if not maestro.hooks[name] then return end
            for i = 1, #maestro.hooks[name] do
                local ret = {xpcall(maestro.hooks[name][i].func, ErrorNoHalt, ...)}
                if ret[1] then
                    table.remove(ret, 1)
                    if ret[1] ~= nil then
                        return unpack(ret)
                    end
                end
            end
        end)
    end
    maestro.hookremove(name, id)
    table.insert(maestro.hooks[name], {id = id, func = func})
end
```
...because there are no PlayerSay hooks.

**Comment by 0tt** [comment]
#2308

**Comment by FPtje** [comment]
DarkRP has always removed PlayerSay hooks. Only at first it removed then at InitPostEntity, now it also removes them when they are created. The problem is indeed viewing the hooks. If I make them visible in hook.GetTable, hook.Call will see them too, which is exactly what I want to prevent.

**Comment by FPtje** [comment]
Besides that commit there's nothing I can do. Sorry. I don't think there's any way to have PlayerSay hooks affect local chat (instead of overriding DarkRP's chat system altogether when returning a value) and still have everything work nicely.

**Comment by MrBrax** [comment]
Maybe there's time to do a global library? ;)))

**Comment by FPtje** [comment]
What do you mean "do" a "global library"?

**Comment by MrBrax** [comment]
CPPI/CAMI thing

**Comment by FPtje** [comment]
nah

**Comment by MrBrax** [comment]
yeh ;))
that distances global and local chat with different hooks for devs to use

**Comment by FPtje** [comment]
Calling all the other chat hooks is the first thing `GM:PlayerSay` does. For all the hooks themselves know, the behaviour is exactly the same as without my hackery. That requires no "interface" to have hooks called even before that, at least not from me.

**Comment by MrBrax** [comment]
![hack](http://rp.braxnet.org/scr/145416212899414.png)

well i'm already using some hacks to get around certain stuff

**Comment by FPtje** [comment]
Jesus christ, this is the second time this week that you complain to me about having issues while failing to give me an accurate description of the problem or what you concretely expect of me. Are you too incompetent to find the god damn "Create Issue" button or to word yourself in such a way that I know even remotely what the fuck is going on?

When you say _"Nuuhh I have problems"_ and _I'm using hacks for my shit to work_, do you expect me to prod you into telling me what the fuck your problem is?

**Comment by MrBrax** [comment]
Since nobody else has reported it before (to my knowledge), i don't find it useful enough to report.. i don't think there's many uses for this (i use it to broadcast ooc chat to steam)
It just wouldn't make sense to implement it in the public release

**Comment by FPtje** [comment]
> Since nobody else has reported it before (to my knowledge), i don't find it useful enough to report..

Not useful enough to report because it hasn't been reported before? By that logic, if anyone has any problem that has not been reported before, should **NOT** tell me because it has not been reported before. That's bullshit.

You may not think there are many uses for the functionality you want. I think differently. Broadcasting OOC chat to steam is an instance of something more generic: doing something right after a player has said something. That can be indeed sending OOC chat to steam, but also logging (certain) chat stuff to a file or even relaying messages to another server.

Even then, coming into a half related issue to say "_I USE HACKS FOR THINGS RELATED TO CHAT_" is bullshit regardless of whether you want to report the issue or not. I truly cannot do anything with that comment.

I can do more with the explanation of what you want to do (relay OOC messages to steam), and I'll fucking look into it.

**Comment by MrBrax** [comment]
I'm not really telling you to do anything, it's just more work for a niche function..

**Comment by Bo98** [comment]
Does [onChatCommand](http://wiki.darkrp.com/index.php/Hooks/Server/onChatCommand) not help?

**Comment by MrBrax** [comment]
@Bo98 true, I made my stuff before that was implemented.

**Comment by FPtje** [comment]
You're not telling me to do or change anything, yet you're complaining that you need to do hacky shit to make your code work. Why the fuck are you complaining if you have **NO** desire even for things to get even remotely better? 

And @Bo98, yes, it would. Not only is @MrBrax complaining about a problem that he doesn't even WANT solved, the complaint is about a problem that is merely the product of his own incompetence.

**Comment by MrBrax** [comment]
I can change it over now, totally forgot about that function. 
And I think differently, apparently it pisses people off sometimes.. Trying to adjust to life but it's hard.

**Comment by FPtje** [comment]
It's simple. When you encounter a bug, a lack of functionality that you think should be there or generally think something can be done better, and that **I**, as the developer am responsible for it, you create an issue on my GitHub describing the issue, and what you think I could do to make shit better.

Example:
"I have to go through weird loops to relay OOC messages to steam. These hoops specifically consist of `InitPostEntity` and redefining the ooc chat commands. <screenshot of code here>"

I am responsible for DarkRP's interface, so you create an issue on DarkRP stating exactly your problem (the hack), how it affects you (screenshot) and maybe even what you'd like to see me do to solve the problem (make a hook available).

Things you should not do:
- Barge into issues that are unrelated. Create your own.
- Complaining without any desire to actually have things improve. I can do NOTHING with your complaint if I don't know what you want from and/or expect of me.
- Describing a problem with "_well i'm already using some hacks to get around certain stuff_", because that comment contains about as much information as saying literally nothing at all.

**Comment by MrBrax** [comment]
Alright, makes sense i guess.
