### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dan2735** [FPtje/DarkRP#2419]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Error thrown at server startup.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Start server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
http://i.imgur.com/z02Bpd9.png

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because only change was updating to 2.7

**Comment by BCBEST** [comment]
I also experience this issue. To give a little more information, this happens when any player joins the server (including bots). 
## Here is a written Error:
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:263: attempt to index local 'data' (a nil value)
  1. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:263
   2. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:302
    3. offlinePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:258
     4. retrievePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:303
      5. restorePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:390
       6. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:585
 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:604: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:604
 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:676: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:676
 
[ERROR] gamemodes/darkrp/gamemode/libraries/fn.lua:252: attempt to index local 'xs' (a nil value)
  1. isMayor - gamemodes/darkrp/gamemode/libraries/fn.lua:252
   2. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:807

**Comment by FPtje** [comment]
Always look for the earliest error, not the last. Not a help forum
