### ISSUE TITLE
Renaming cr (combinerequest)

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2420]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Since the Police is not a Combine in literally every server, I would change the commandname to something different like /pr for police request.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
No bug

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No bug

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
No bug

**Comment by Shigbeard** [comment]
C.R.

Cop. Request.

/issue

In all seriousness though, I have enough issues introducing communities 
to the concept of /cr, a command that has been in existence since before 
DarkRP 2.4.3. Renaming it to /pr will just cause more confusion.

If anything, there should be some aliases to /cr, such as /coprequest or 
/emergency.

Not that anyone will use it. They will still just do /ooc ADMIN TO ME

**Comment by FPtje** [comment]
Aliases, yes, no renames

**Comment by mcNuggets1** [comment]
Nobody uses /cr because nobody is aware of it.

**Comment by fruitwasp** [comment]
Better add /911 as an alias

**Comment by FPtje** [comment]
There used to be a 911, but I don't know what happened to it.

**Comment by Bo98** [comment]
/911 used to be for when you were _attacked_ exclusively. When it was removed, the whole command was removed.

**Comment by FPtje** [comment]
Yeah, I remember, it was Eusion's thing.

**Comment by Hazbelll** [comment]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Since 911 is not the emergency number in literally every country, I would change the commandname to something different like /eno for emergency number.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
No bug

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No bug

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
No bug

**Comment by FPtje** [comment]
I thought about that, add /911, /999, /112, /000

https://en.wikipedia.org/wiki/List_of_emergency_telephone_numbers

It won't be all of them, but it should do.

**Comment by BillyOnWiiUIn144p** [comment]
Wait what? /cr is a thing?

![](http://billyvenner.xyz/files/hl2_2016-04-17_17-24-15.png)

**Comment by Shigbeard** [comment]
Why not /emergency

/help

/admintome?

I'm going on 30 hours no sleep here, forgive me if im posting cancer

**Comment by FPtje** [comment]
"/admintome"!? Seriously? That should be an alias for `disconnect`, not /cr

**Comment by Hazbelll** [comment]
`/summonfalco` perhaps?

**Comment by FPtje** [comment]
Only if there's a song to reply to that

**Comment by Shigbeard** [comment]
>only in there's a song to reply to that

Something like this?

http://vocaroo.com/i/s15MuhiwRadH

Lyrics because i suck at audio:

> Your printers just got stolen
> or maybe you were shot
> Theres tons of cops around you
> but all you do is shout
> 
> "ADMIN TO ME 
> RDM NLR METAGAME
> BAN HIS FUCKING ASS RIGHT NOW
> CAUSE HE IS REALLY LAME"
> 
> Just grow a fucking pair kid
> This is not the admin's hunt
> Use /cr to get the cops help
> You massive fucking cunt

**Comment by FPtje** [comment]
Fucking amazing

**Comment by BillyOnWiiUIn144p** [comment]
Brilliant

**Comment by Shigbeard** [comment]
More like shit, I spewed listening to myself and my shit tier microphone.

**Comment by FPtje** [comment]
Of course it could use some improvement, but the fact that you did it is
amazing.
