### ISSUE TITLE
Strange comments...

### ISSUE THREAD

**Issue by PhiLhoSoft** [FPtje/DarkRP#2434]
I see, in files like https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua or https://github.com/FPtje/DarkRP/blob/master/gamemode/config/licenseweapons.lua lines like:
```
/*---------------------------------------------------------------------------
Some comment
---------------------------------------------------------------------------*/
```
Is it supposed to work with the Lua dialect used in Garry's Mod? (I doubt it...)
Other files use more classical `--[[ ... ]]` for block comments, and a quick search on Internet shown nothing about supporting C-style comments.
If that's an error (and even if that's not one!), I suggest to change to the idiomatic Lua style.

Note: I don't play at this game, I just saw this code on my son's computer...

**Comment by Bo98** [comment]
> Is it supposed to work with the Lua dialect used in Garry's Mod?

http://wiki.garrysmod.com/page/Specific_Operators

But yeah, I agree that it should be made consistent throughout the code base.

**Comment by FPtje** [comment]
Eh, perhaps.

**Comment by PhiLhoSoft** [comment]
OK, I didn't expect to find comments under an "operator" category... :smile: 

Side note: sticking to classical Lua helps GitHub to correctly highlight your files... :laughing: Same for text editors, etc.

Personally, I dislike these kind of mods, where users of a language try to mimic another language, instead of embracing the idiomatic way.

**Comment by FPtje** [comment]
I disagree. The reason why can be summarised in one keyword: continue. Lua
doesn't have it, and if I recall correctly, the reasons for not having it
are pretty arbitrary. Gmod lua does have it, and it makes my code a lot
more readable. The continue keyword shows that modding a language can be
very useful indeed.

I understand your critique and even agree when it comes to operators and
comments. Garry's reasons for adding `&&` as an alias for `and` are even
more arbitrary than Lua not adding `continue`: he just couldn't get used to
them. C style comments and operators serve no purpose whatsoever. In fact,
Lua multiline comments are more powerful than their C equivalents, since
they support nesting.

The reason why DarkRP has C style comments is because of age. I was taught
to work with C comments and only even added Lua multiline comment snippets
to my Sublime text editor GLua Plugin recently.

**Comment by PhiLhoSoft** [comment]
I agree on the continue statement, but it is an additional feature, not disguising native operators to look like something else. That's a different topic. I cringe at the latter, not necessarily at extending the language.
Latest version of Lua has goto, reducing the need for continue (ie. you can do the same thing with it).

Anyway, we drift.
I initially feared these comment were a mistake, but they are valid in the context of these scripts.
Beside the inconveniences I mentioned (syntax highlighting), I suppose they can be left as is.
That's your call, feel free to close this thread with or without changes. :smile:

**Comment by FPtje** [comment]
Text editors are no problem, since both atom and Sublime have highlight and even linter plugins
