### ISSUE TITLE
FSpectate breaking serverguard spectate

### ISSUE THREAD

**Issue by SomeSortOfDuck** [FPtje/DarkRP#2478]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The spectate chat command being overriden for [this](https://scriptfodder.com/scripts/view/1847) admin mod.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Try to spectate with serverguard installed using "!spectate \<player>" in chat. The expected result is serverguard spectating the player. The actual result is FSpectate spectating the player.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
You're breaking functionality in another addon. A gamemode shouldn't even be adding spectate commands in the first place. At least remove the serverguard command (both client and server) if you're going to do this.
```lua
serverguard.command:Remove("spectate")
```

**Comment by FPtje** [comment]
FSpectate is kind of designed to override other admin mods' standard commands. The reason is because FSpectate is specifically designed for spectating. With very few exceptions, the spectating of admin mods, including serverguard, every player knows who is spectating who at all times. Minges stop minging when the admins are looking. Even if the admins are on the other side of the map, the minges will know right when the admins start spectating. With FSpectate, this is not the case.

**Comment by SomeSortOfDuck** [comment]
But you're breaking functionality in another addon. At least remove the serverguard command if you're going to do this.

**Comment by FPtje** [comment]
Done
