### ISSUE TITLE
DarkRP Modifications require different include() paths server/client side 

### ISSUE THREAD

**Issue by bbblitz** [FPtje/DarkRP#2522]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When creating a darkrp addon, the customthings/entities.lua include() requires an additional directory backtrack when executed server side, but not client side. (I have not tested any other files)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Copy the example DarkRP addon, and set the folder structure like this
```
darkrpmodification/
    lua/
        darkrp_customthings/
            entities.lua
        some_config.lua
```
entities.lua
```
local config = include("../some_config.lua")
print("I'll make my entity cost:",config.what)
```

some_config.lua
```
AddCSLuaFile()
local cfg = {}
cfg.what = 10
return cfg
```

As an additional note, if entities.lua is set up like this instead, it will work fine.
```
local config
if SERVER then
    config = include("../../some_config.lua")
else
    config = include("../some_config.lua")
end
print("I'll make my entity cost:",config.what)
```

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
(blue error)
```
Couldn't include file '..\some_config.lua' (File not found)
(@addons/darkrpmodification/lua/darkrp_customthings/entities.lua (line 19))
```

Then some time later
(blue error)
```
[ERROR] A runtime error has occurred in "addons/darkrpmodification/lua/darkrp_customthings/entities.lua" on line 21.
The best help I can give you is this:

attempt to index local 'config' (a nil value)

Hints:
	- No hints, sorry.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification/lua/darkrp_customthings/entities.lua on line 21
	2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 137
	5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 148
	6. gamemodes/darkrp/gamemode/init.lua on line 86
------- End of Simplerr error -------
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
(I think) I should be able to include the file on either server or client with the same include command, since the file (should?) is not in different places between the server and client.

**Comment by FPtje** [comment]
With this folder layout:
```
darkrpmodification/
    lua/
        some_config.lua
```
(directly copied from your example), you can include some_config using just `include("some_config.lua")`, since that file is top level in the Lua directory.

**Comment by FPtje** [comment]
The reason this happens is because of [simplerr](https://github.com/FPtje/simplerr), a library I made to translate error messages. On the server it runs things in a special wrapper to be able to catch errors and explain them to the user. One of the effects of this is that relative paths go to shit. Because of restrictions in GMod I cannot fix this while still having those nice error messages. I want my nice error messages, so I won't do anything to solve this particular issue. There are some things you can do though:

- Add `#NoSimplerr#` to the top of your Lua files, or anywhere in a comment. That should solve this problem.
- Stop using relative paths, load `some_config.lua` like this: `include("some_config.lua")`. This might be an unreasonable thing to ask if you made a module in the `darkrp_modules` folder.
- The if statement you described, although that might not be future proof, since an update might give me a better method to catch errors, which I would use if I could.
