### ISSUE TITLE
DarkRP player's issue.

### ISSUE THREAD

**Issue by Pingu12** [FPtje/DarkRP#2527]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Player's join as job named '' Unassigned''. Not all of them, only few inviduals, and the console erros start getting spammed. You can change their jobs and the errors stop, but they may not play like they should.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Bug happens as soon as the some player joins.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[Connections | 08:56:10]Matt(STEAM_0:0:142134477) has connected
 
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sv_data.lua" on line 427.
The best help I can give you is this:
 
Failed to retrieve player information from the database.
 
Hints:
    - This means your database or the connection to your database is fucked.
    - This is the error given by the database:
        column rpname is not unique
 
The responsibility for the error above lies with (the authors of) one (or more) of these files:
    1. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 427
    2. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 313
    3. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 299
    4. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 243
    5. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 287
    6. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 304
    7. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 267
    8. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 312
    9. gamem
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua" on line 384.
The best help I can give you is this:
 
There is a player with an invalid team!
 
The player's name is Matt, their team number is "1001", which has the name "Unassigned"
 
Hints:
    - It is the server owner's responsibility to figure out why that player has no valid team.
    - This error is very likely to be caused by an earlier error. If you don't see any errors in your own console, look at the server console.
 
The responsibility for the error above lies with (the authors of) one (or more) of these files:
    1. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 384
    2. gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua on line 605
------- End of Simplerr error -------

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Developer of DarkRP is probablly the best person to ask for the help, obviously. Since he probablly does know how to handle this ''Simple'' problem. Also server is not being runned on MYSQL.

**Comment by Bo98** [comment]
Updating DarkRP should fix this. RP names used to have to be unique. This had the side effect of affecting people who happened to have a Steam name matching an existing RP name. This was fixed in June.

**Comment by Pingu12** [comment]
Alright, thank you for the repply. Hopefully this will fix the issue.

**Comment by Pingu12** [comment]
After updating Darkrp, i am not able to use /advert anymore. when i try to use advert ( exmp. /advert hey ) it states that '' This model of entity is blacklisted ''

**Comment by Bo98** [comment]
No idea why the blacklist is having any affect on that. If it did then /placelaws wouldn't work either (both commands use the billboard model). Are you using FPP or something else?

**Comment by Pingu12** [comment]
Yes, i do use FPP. Before i've updated the DarkRP, it worked like it should. so what should i do for it to work again?

**Comment by Bo98** [comment]
Does /placelaws work?

**Comment by Bo98** [comment]
I think I figured why it isn't working. It's a part of FPP's protection against the likes of Wiremod E2s from using blocked models. You could either unblock "models/props/cs_assault/Billboard.mdl" or alternatively check "Apply to props only" under "Blocked model settings" if you don't use stuff like E2s.

Though perhaps something should be done so that this isn't necessary - I'll have a look and see.

**Comment by Pingu12** [comment]
Yes, it does work.

**Comment by Pingu12** [comment]
Alright, i've done "Apply to props only" under "Blocked model settings". Now adverts are being spawned like lawboards, which is horrible. http://imgur.com/a/8JKqr

**Comment by Bo98** [comment]
It's supposed to do that. It was changed a couple months ago due to very heavy abuse of the old /advert command - now it actually represents an advert rather than a logging system some servers had adopted. (Though with your "help me" request that can still be done with /cr or /911 which is sent directly to the cops/police.)

**Comment by Pingu12** [comment]
Oh god. I wasn't aware of that. Any possibility to use the /advert like before? I don't really think spawning boards to say youre mugging/kidnapping/raiding them is really thing i need, but thats just mine opinion.

**Comment by Bo98** [comment]
> to say youre mugging/kidnapping/raiding them

That type of stuff really should be done differently than announcing it globally to the whole server. I'm not entirely sure what you're reasoning behind the rule was (different people have stated different reasons) but there are alternatives like having the victim contact the police or incorporating a system where instead of announcing publicly, it logs it only for admins to see, depending on what you were trying to achieve from such a rule.

> Any possibility to use the /advert like before?

Officially, no. I have no idea if any addons exist that restore the command but I do recommend thinking whether you really need it as there have been people I've talked this with that have realised that there was in fact better solutions instead of the old system. If you do use the old system, do remember that it isn't supported anymore by the DarkRP developer so any issues that arise with it won't be fixed.

**Comment by Pingu12** [comment]
Alright then, it looks like ill have to get used to the new ways of the Darkrp. Thanks anyways.

**Comment by Bo98** [comment]
I'm happy that you're at least trying to do so. I know it's a big change but at least you aren't arrogant [like some people were](https://github.com/FPtje/DarkRP/issues/2479). If you're not sure about new ways to approach things then let me know and I'll try come up with suggestions.
