### ISSUE TITLE
Over Head Hud

### ISSUE THREAD

**Issue by BasonTaylor** [FPtje/DarkRP#2541]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I apologize but i use a normal hud and we do serious rp and i am looking to disable over head hud so when sneaking or any thing of that nature people can not look in the general direction and see the over head hud. But when i disable it it sends this error back when i do /rpname BOB or any type of chat command. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
disabled the hud.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

Warning: Unhandled usermessage '_Notify'

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
its your hud.

is there a way around this?

**Comment by Bo98** [comment]
Instead of disabling the HUD module, try disabling the individual HUD elements in the "hudreplacement" module in the DarkRPModification addon (https://github.com/FPtje/darkrpmodification/blob/master/lua/darkrp_modules/hudreplacement/cl_hudreplacement.lua#L5-L36).

The notifications that come up at the bottom right of the HUD are included when disabling the HUD module which is why you are getting that warning. It's the server sending a message to the client to display the notification but the client doesn't know what to do with it if the HUD module is disabled. I guess it was done this way as it could be seen as a piece of HUD that addons may want to customise but I would've said overriding the notification library was better since GMod handles what notifications look like rather than DarkRP.

**Comment by BasonTaylor** [comment]
so this should be true?

**Comment by BasonTaylor** [comment]
-- DarkRP_EntityDisplay is the text that is drawn above a player when you look at them.
	-- This also draws the information on doors and vehicles
	["DarkRP_EntityDisplay"] = false,

**Comment by BasonTaylor** [comment]
thank you :)
