### ISSUE TITLE
HUGE PROBLEM....

### ISSUE THREAD

**Issue by claytonfox1** [FPtje/DarkRP#2576]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
You got rid of adverts and made a stupid board. Please add adverts back.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by skyrpowner** [comment]
Use https://github.com/WilliamWelsh/classic_darkrp_advert if you want to fix it, all you do is drag it into addons and use /ad for advert.

**Comment by Shigbeard** [comment]
Your regular tv scheduling will resume after these short messages from our sponsors:

"HEY EVERYBODY DID YOU KNOW I'M RAIDING SOME POOR FUCKS SHIT RIGHT NOW?"
"JUST LETTING YOU KNOW I'M MUGGING THIS FUCK IN BROAD DAYLIGHT FOR 20 THOUSAND DOLLARS!"

What I'm trying to say here is you wouldn't advert your crimes in real life, you would keep them hush hush, maybe telling your closest friends. So now, instead of having it as a text chat log, it is now an actual advertisement you have to place somewhere.

You are literally autistic if you want the old system back.
