### ISSUE TITLE
cl Error

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2602]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Erroring

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Unknown

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] lua/includes/util.lua:181: attempt to index a string value with bad key ('IsValid' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:301
    3. IsValid - lua/includes/util.lua:181
     4. func - gamemodes/darkrp/gamemode/modules/chat/cl_chat.lua:28
      5. unknown - lua/includes/extensions/net.lua:32

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Mkay

**Comment by fruitwasp** [comment]
bug introduced in https://github.com/FPtje/DarkRP/commit/3c48262b335912f7c314686bc714810df8372cd7

**Comment by FPtje** [comment]
This is why I program in Haskell nowadays.

**Comment by Kefta** [comment]
@FPtje More of a Source thing than a Lua thing

**Comment by FPtje** [comment]
Lua may not natively have `NULL`, but it still has nil and dynamic typing.

**Comment by Kefta** [comment]
Dynamic typing has its pros and cons, but with nil, it's very easy to check since in if-statements, it essentially equivocates to false. I just wish NULL did the same.

**Comment by FPtje** [comment]
Forgetting to check is even easier than the actual check.
With every single object you ever do anything with, you have to take into account that it just might be NULL or nil. In most languages moreso with NULL than nil. In C#, shit can't be nil, but they *can* be null.

Null is probably the single biggest source of bugs in languages that have them.

**Comment by Kefta** [comment]
Sure, but objects just don't go out of scope and become null randomly. In C++, a pointer or object doesn't become NULL until you destruct it yourself, or you get rid of all references. In GLua, entities aren't NULL unless you cross realms, use them too early (only applies to LocalPlayer, really), or hold onto a reference of them for longer than a tick.

**Comment by FPtje** [comment]
Players being null at the start of the game is actually the perfect example
of the situation being terrible. It's not just that you use LocalPlayer top
level in an autorun script. With every net message you receive, every
usermessage and probably some hooks, you have to account for the fact that
they might just arrive/be run before localplayer is initialised. It's easy
to miss, first of all, but the fact that the code looks perfectly fine and
just works fine most of the time is what makes it really nasty.

Contrast this with `Maybe` in Haskell. A `Maybe` is either `Nothing` or
`Just something`. Now imagine that LocalPlayer was in a Maybe. When you
want to do stuff with the player, you have to take it out of the Maybe.
Acting like the Maybe isn't there and treating it directly as a player
would give a type error. You **have** to either write code for both when
it's Nothing or Just, or explicitly say that you just assume that the
player isn't `Nothing`. The difference between assuming the player isn't
`Nothing` differs from assuming that the player isn't NULL in that the
former assumption is explicitly written down in code and the latter comes
about from the lack of code (that checks against null).


On 15 Dec 2016 9:59 p.m., "Collin (code_gs)" <notifications@github.com>
wrote:

Sure, but objects just don't go out of scope and become null randomly. In
C++, a pointer or object doesn't become NULL until you destruct it
yourself, or you get rid of all references. In GLua, entities aren't NULL
unless you cross realms, use them too early (only applies to LocalPlayer,
really), or hold onto a reference of them for longer than a tick.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/FPtje/DarkRP/issues/2602#issuecomment-267442262>, or mute
the thread

**Comment by Kefta** [comment]
The 'Maybe' can be eliminated in this case by sending a net message to the server when the LocalPlayer becomes valid on the client. Until then, the server does no work involving LocalPlayer, and so there's no need to have a 'Nothing' case.

**Comment by Bo98** [comment]
The "Maybe" stuff reminds me of the "optionals" stuff a lot of new languages have, such as Swift and Kotlin. It's indeed quite a nice way to work.

**Comment by FPtje** [comment]
@Kefta my argument only involved the server in the sense that it could send messages to the client that could arrive before Localplayer was valid. What do you mean by having the server deal with LocalPlayer?

I mean sure, you can have the client tell the server when it's ready, but the moment you start writing the code for that, you must already be aware of the problem in the first place. You could also have the client hold on to messages until after InitPostEntity, reject messages before InitPostEntity or just do the NULL check. There are plenty of ways to avoid a NULL error, of course. The problem is that with all the many places in code where it can occur, it is *very* likely that null checks are forgotten in at least a few of these places. This means that even experienced developers have to test their software extensively and fix a bunch of NULL errors before release, and that even then years later someone might manage to hit the extremely rare case where a net message arrives before some object is valid. 

With the Maybe alternative I mentioned, the language *itself* reminds you to properly deal with the fact that an object is not there (yet or anymore). You can still make the mistake of forgetting to deal with Nothing, but the only way to do that is to *explicitly* say "take the thing out of the Maybe and just assume it's not Nothing". In Haskell this can be done by using the `fromJust` function. When you use it, you *consciously* take a risk. With NULL, the risk is just there with every entity or object that your code reasons about, unless that object is reasoned about within a single Lua iteration, after InitPostEntity and without interop.
