### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2663]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
1.[ERROR] gamemodes/darkrp/entities/weapons/weaponchecker/shared.lua:241: attempt to call method 'SetClip1' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/weaponchecker/shared.lua:241

2.[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/messaging/cl_init.lua:178: attempt to index local 'notification' (a nil value)
  1. func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/messaging/cl_init.lua:178
   2. unknown - lua/includes/extensions/net.lua:32

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by strideynet** [comment]
When/where does this occur?

**Comment by FPtje** [comment]
I second that motion, on both errors. The first one happens when you confiscate and then return a weapon that doesn't exist. The second error happens when an FAdmin notification is sent that isn't registered clientside. Both can otherwise happen with interference from other addons. I need more information.

**Comment by mcNuggets1** [comment]
The FAdmin thing only happens clientside and often for joining players.

The weapon checker thing happened 1 day alot of times, but I never saw this happening again.

**Comment by strideynet** [comment]
Can you get the fAdmin error to replicate on a server with only DarkRP installed? If not this is most likely another addons problem, as they aren't registering it on the client correctly. If you can provide a list of addons we can probably work out who it is and contact them so that they can resolve this.

**Comment by FPtje** [comment]
Run `lua_run_cl PrintTable(FAdmin.Notifications)` in client console and `lua_run PrintTable(FAdmin.Notifications)` in server console. The server probably has some entries more than the client.

Also, both client and server should have at least 29 entries. You're doing it wrong if they don't.

**Comment by mcNuggets1** [comment]
Its the same.

It does not happen regularly, rather rare.

**Comment by FPtje** [comment]
This isn't the kind of thing that happens to some people only unless they've hit a lua limit or some shit. This is probably caused then by some seriously broken game state.
