### ISSUE TITLE
Error still happening

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2665]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
[ERROR] gamemodes/darkrp/entities/entities/fadmin_jail/init.lua:26: Tried to use a NULL entity!
  1. SetPos - [C]:-1
   2. unknown - gamemodes/darkrp/entities/entities/fadmin_jail/init.lua:26

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Kefta** [comment]
It looks like Replace is creating a NULL entity, which was the whole issue me and Falco discussed a few issues ago and he added a "fix" for. Are you sure that there is no error before that saying you hit the entity limit?

**Comment by mcNuggets1** [comment]
3905 Entities

**Comment by FPtje** [comment]
`#ents.GetAll()` isn't a valid way to count entities. There might be fewer entities reported by `#ents.GetAll()` while still being on the limit.

There's no better way, so this'll have to do.

**Comment by mcNuggets1** [comment]
I actually ran it serverside. How is that not trustworthy?

**Comment by mcNuggets1** [comment]
There is not even a "hit entity" limit message.

**Comment by FPtje** [comment]
The function doesn't return all entities. Counting the table will therefore not count all entities.

**Comment by mcNuggets1** [comment]
Does the new function ents.GetCount function better?

**Comment by FPtje** [comment]
Wiki says no.

> Same as #ents.GetAll only with much better performance.

**Comment by Bo98** [comment]
> There is not even a "hit entity" limit message.

So no `Not creating entity 'fadmin_jail' - too many edicts! (XXXX current, 8192 max)` line in _console_?

**Comment by mcNuggets1** [comment]
I just found out the error appeared after the server was shut down.

That has to be a gmod bug then.

**Comment by FPtje** [comment]
The error itself probably didn't crash the server. It would be more likely that something else caused both the crash and the error.

**Comment by Bo98** [comment]
So it was gracefully shutting down, then the error occurred and then something happened that caused the server to crash?

Are you able to reproduce the error part every time by FAdmin jailing someone and then gracefully shutting down the server?

**Comment by mcNuggets1** [comment]
It should have changed map, but due to the error shut down as far as I can see.

**Comment by Bo98** [comment]
`OnShutdown` is called on changelevel too so that would count as 'graceful shutdown' from a Lua point of view.

Still, can you reproduce the error by jailing someone and then changing the level while they are still jailed?

**Comment by mcNuggets1** [comment]
It does not happen regularly.

But it always errors on weapon_fists or the darkrp-jails.

**Comment by Bo98** [comment]
What's the weapon_fists error, out of interest?

**Comment by mcNuggets1** [comment]
I don't know it out of the head, cause I fixed it, but it had to do with the UpdateIdle function.

**Comment by Bo98** [comment]
I'm able to reproduce the jail error no problem.

Seems that GMod still calls `OnRemove` on entities when removing them on shutdown (or changelevel). This is causing an infinite loop in `fadmin_jail`, as it keeps trying to replace the removed entity. When GMod is in this state, it doesn't seem to block the creation of new entities, so it'll be adding entities to the entities list while GMod is removing them. The loop is only terminated by the entity limit.

DarkRP's error does not throw as `#ents.GetAll()` returns a constant value during this time, since `ents.GetAll()` does not include entities marked for removal, but the actual removal of the edict (and therefore the decrement in the number of entities counting towards the limit) only happens later. **`ents.GetCount()` does not suffer this issue** (though you'll have to wait a week for the update to release that includes it).

`fadmin_motd` has similar code but it doesn't actually work, since the `target` field is never set.

The reason you did not notice GMod's entity limit error message is because it never gets logged to the server logs. It appears in console only (and console.log probably if you have that enabled).

The crash is reproducible on the dev branch. It's caused by MySQLOO (though could be a bug with GMod's binary module changes) and it completely unrelated to the Lua error. In fact, it happens every time I changelevel when the server is not hibernating. I will report this.

**Comment by FPtje** [comment]
Oh wow

**Comment by Bo98** [comment]
The behaviour of `ends.GetCount()` is getting changed unfortunately so switching that won't help the accuracy of the error in the long term:

https://github.com/Facepunch/garrysmod-requests/issues/953

**Comment by Kefta** [comment]
I posted a better solution, but FL_KILLME entities are only around for a tick, anyway, so it would only affects very rare edge cases. I would recommend printing a message before the user hits the entity limit to warn that they're getting close.

**Comment by Bo98** [comment]
How long are edicts around for after `FL_KILLME` is set then? An arbitrary amount of time?

**Comment by Bo98** [comment]
Or are you referring to the function not differentiating between networked and non-networked entities?

**Comment by Kefta** [comment]
Both, and the edict is around for a tick

**Comment by Kefta** [comment]
```
STORE = {}
local len = 1
local p = ents.Create("prop_physics")

repeat
	p:SetModel("models/player.mdl")
	p:Spawn()
	p:SetMoveType(MOVETYPE_NONE)
	p:SetCollisionGroup(COLLISION_GROUP_NONE)
	STORE[len] = p
	len = len + 1
	
	p = ents.Create("prop_physics")
until(p == NULL or len == 10000)

print(ents.GetCount(), ents.GetEdictCount(), #ents.GetAll())
```
Output:
```
Not creating entity 'prop_physics' - too many edicts! (8176 current, 8192 max)
8291	8176	8291
```

Seems like its working.

**Comment by FPtje** [comment]
Nice! I didn't know that function was added. Thanks @Kefta!
