### ISSUE TITLE
Suggestion: resource files

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2675]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I would suggest adding a config setting to disable automatic resource file downloading as I resource it via workshop. (+ fadmin files)

**Comment by FPtje** [comment]
I don't know much about the download system, but don't files get ignored when you already have them? I don't think there's much of a difference in files between workshop and fastdl for DarkRP, since DarkRP isn't that big.

**Comment by mcNuggets1** [comment]
I don't know anything about the download system either, but in alot of cases, even if the workshop addon is subscribed to, darkrp tries to force the players to download resources.

Maybe workshop addons mounts after resources are downloaded.

**Comment by Kefta** [comment]
That is correct

**Comment by FPtje** [comment]
That asks for a somewhat more rigorous approach than just allowing people to disable downloads.

**Comment by mcNuggets1** [comment]
Let's rewrite the download system?

**Comment by FPtje** [comment]
Here's the situation: DarkRP always sends the files to the client. Supposedly regardless whether the client is subscribed to DarkRP and regardless of whether the server is running the workshop version or the Github version.

If you use the workshop version, clients will get the necessary stuff regularly. They **won't** download a copy of the gma. That has the benefits that people don't download serverside files, but that's minor. The big benefit for me is that things are the same between the workshop and github version of DarkRP. That's a really big one.

Using the workshop to get the clients their shit is a huge pain in the ass. I can't have the Github version send the workshop version to the client because the changes in versions can lead to some seriously fucked up errors and problems that are crazy hard to reproduce and debug. That and DarkRP could gradually break for everyone not updating the Github version often enough. To have the workshop version not send its shit through `resource.AddFile` would also be a pain because then the code would have to be different between the Github version and the Workshop version. I currently never test the workshop version because it's exactly the same, with files being in a different location. Different code can cause issues in the workshop version that don't exist in the Github version, and I'm not in the mood to deal with that.

Don't have clients download the workshop version of DarkRP. They'll get what's necessary the regular way. Download speed is a non-issue for DarkRP anyway.

**Comment by mcNuggets1** [comment]
I don't fast-dl darkrp files, so the download is pretty useless.
