### ISSUE TITLE
Ability to add hidden jobs from F4 menu

### ISSUE THREAD

**Issue by Noname12345GER** [FPtje/DarkRP#2685]
Not a Bug report, but more a suggestion.
I know there is a config option for Custom-Check-Failed Jobs, but i need it for something else already.

Could be added in the custom job fields.

hidden = true,

Edit: This might go better at DarkRP-modification?

**Comment by FPtje** [comment]
They are visible and greyed out by default.

**Comment by Noname12345GER** [comment]
So there is no way to hide them?

**Comment by FPtje** [comment]
```
-- hide the items that you can't buy and the jobs you can't get (instead of graying them out).
-- this option hides items when you don't have enough money, when the maximum is reached for a job or any other reason.
GM.Config.hideNonBuyable = false

```

**Comment by Noname12345GER** [comment]
Please let me try to describe it better :)

-I know that this option is aviable.

-I have some Donator Jobs with SHOULD STILL be displayed EVEN if customcheck fails.

- I have a Deathmatch Job with is for an Arena and with is assigned by an entity. But this Job should be hidden from Job category.

If I am using the config can surely hide my Arena Job BUT it will hide my Donator Jobs aswell.

I am looking for an ability to hide certain Jobs from F4 regardless of the visibility Settings in the config.

Can you understand me now what I'm trying to describe?

**Comment by FPtje** [comment]
Hide by default and use the `or CLIENT` trick in the customCheck.

**Comment by Noname12345GER** [comment]
Wow that's Smart.

**Comment by Noname12345GER** [comment]
Mind if I ask you something about your perfect RP concept?

**Comment by FPtje** [comment]
Sur3

**Comment by Noname12345GER** [comment]
Some people get on and kinda Freak out because they see RDM is allowed. Since there are no Police officers, one will join it and it will be only Deathmatch at Spawn. How would I deal with it?

**Comment by FPtje** [comment]
With more lax rules, the focus of administration lies less on those who break specific rules, and more on those with malicious intent.

You can pretty easily catch people trying to mess up the server if you look when the deathmatch starts. Punish those on sight. Talking to them on a roof will encourage them to fuck shit up more. 

Finding the instigator is pretty much impossible when everyone is killing everyone, though. People get dragged along. The key there is to stop the cycle of "I'm killing everyone because everyone is killing me". One way to do that is to freeze the entire server, warn that the next player who spawn kills in the next X minutes gets kicked on sight and then unfreeze everyone. Then watch spawn for those minutes and act upon your warning. 

These are methods I've used in the past, but their appropriateness heavily depends on the situation. Find your own twist, discuss methods with your admins, try to find out what works and what's best for the players.

**Comment by Noname12345GER** [comment]
Can you add this to your MOTD?

**Comment by FPtje** [comment]
It's probably best to keep that short.

**Comment by Noname12345GER** [comment]
More to the Google Docs contained in the MOTD.
