### ISSUE TITLE
Fadmin Issue, No ranks or anything

### ISSUE THREAD

**Issue by Jewsie** [FPtje/DarkRP#2703]
Hey I have had this Error pretty often now, idk if there are some addon that can be conflicting, but I think I don't know. Maybe it's something else I haven't been able to find out what it is, and FAdmin fucks up almost everytime, it worked and after I restarted the server, then this happend.

[DarkRP] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:260: attempt to index field 'user' (a nil value)
  1. DoClick - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:260
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_controls.lua:301

**Comment by strideynet** [comment]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)


### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)


### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)


### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

What part of "Do not remove this template" are you unable to understand?

**Comment by Bo98** [comment]
Are you using the latest version of DarkRP? The line numbers suggest not.

**Comment by FPtje** [comment]
These members of the table are hard coded. I'm going to blame files not being downloaded properly or their CRC conflicting with other files.
