### ISSUE TITLE
Error logs tipjar

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2704]
### Lua errors
[ERROR] gamemodes/darkrp/gamemode/modules/tipjar/cl_communication.lua:29: attempt to call method 'Donated' (a nil value)
  1. func - gamemodes/darkrp/gamemode/modules/tipjar/cl_communication.lua:29
   2. unknown - lua/includes/extensions/net.lua:32

Version: Github last

**Comment by FPtje** [comment]
Either caused by a third party, or you're omitting an error. The server is sending a `DarkRP_TipJarDonate` message to a client with an entity that isn't a tip jar (or for some other reason doesn't have a `:Donate` function, which tip jars do have). The only place where the server sends that message (https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/tipjar/sv_communication.lua#L47) is after checking whether the entity really is a tip jar.
