### ISSUE TITLE
issue with cs lua being allowed

### ISSUE THREAD

**Issue by cactusadmin** [FPtje/DarkRP#2732]
[//]: # (DO NOT REMOVE THIS TEMPLATE.) ok. why?
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP) yes they are thats why its called "issues"
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ ) no, your forums are a maze to find a solution.

Can't seem to disable allow cs lua, which I am trying to do yet apparently darkRP overrides that. need to know where to force cs lua to be disabled at in the gamemode.

###Why the developer of DarkRP is responsible for this issue
Because its your gamemode and this issue should have never been possible to happen in the first place. you should really fix it

**Comment by strideynet** [comment]
Do us all a favour and go fuck yourself. No one owes you anything.

**Comment by FPtje** [comment]
It's in the config of the DarkRPMod.

Also @strideynet what the fuck

**Comment by strideynet** [comment]
In retrospect, I may have been a little harsh there. But you are clearly disregarding the purpose of this issue system and you really aren't helping yourself. 

Other people have been able to prevent CS lua execution so it's clearly something to do with your configuration, likely to do with whatever other add on you have installed. 

If you want any chance of getting help here, you need to abide by the system in place and give all the information you can. You can't waltz in expecting people to go out of their way to help you, especially considering they have no obligation to do so.

**Comment by conorstewart** [comment]
Must say I have to agree with that one

**Comment by Kefta** [comment]
Let Falco handle that, it's not your job to flame other people.

**Comment by cannon** [comment]
did you try sv_allowcslua 0

**Comment by Noiwex** [comment]
Hey falco, I have sv_allowcslua 0 but your gamemode for some reason sets it to sv_allowcslua 1. Why does it change my config?

**Comment by cannon** [comment]
IDK why you'd ever want to enable that convar anyway, except for testing. Maybe falco likes to go around hacking on servers which use his gamemode?

**Comment by roboderpy** [comment]
Exploits used in addons installed on server through clientside lua are purely server coder's fault. Clientside lua can't be used to "hack" the server, but if server use bad coded addons that can be easily exploited users can "hack"  the server

**Comment by cannon** [comment]
Yeah but they can still XRAY or something. Not saying they can't get around allowcslua anyway, but why would you ever want to invite it like that?

**Comment by roboderpy** [comment]
Isn't usage of cheats show intelligence level of players who use them? They just don't know how to play properly, so they use cheats. I know, sometimes it is painful to detect, find, laugh on and ban a kiddo cheater, but on my point of view clientside lua is great. And yes, if you are unable to disable cslua, you are doing something wrong because disabling cslua in darkrp works for me although i don't do that because legal players want their fancy stuff run clientside on their favorite servers.

**Comment by Noiwex** [comment]
Sure, let's give them easy way to cheat. Who uses custom huds nowadays? I'm pretty sure every server owner just ripped that sv_allowcslua 1 nonse out of their server code anyways.

**Comment by FPtje** [comment]
@Noiwex you know my reasons for changing the allowcslua default. I've told you a million times. Stop acting like this shit is new to you and that you're taken by surprise with this behaviour. That's just stirring shit.

**Comment by cannon** [comment]
can you please inform me why? I am not a dark rp man

**Comment by FPtje** [comment]
Before allowcslua there was scriptenforcer. Scriptenforcer was off by default, meaning you could run clientside scripts. Non-sandbox gamemodes servers turned it on, because clientside scripts can give an unfair advantage. In Sandbox however, there was this whole community of useful clientside scripts. There was smartsnap that helped build precisely, there were spectate addons, menus with buttons to commands that were otherwise unknown to most people, scripts to make your own hotkeys and way more. In gamemodes like sandbox, those scripts were great. You could download them and use them in any server that allowed it.

DarkRP, originally being sandbox with non-serious RP elements added, has users benefit from clientside scripts. A while ago I made a script (and module) with which I can connect my yamaha keyboard to gmod and play MacDGuy's piano using my actual keyboard. That means I can play way more complicated songs than that shitty rendition of that Coldplay song everyone does. That's great RP fun, but making the script would be a waste of time if literally no server allowed CS lua.

Garry changing the default of allowing clientside Lua was a serious mistake. He killed off basically the entire clientside scripting community. I decided that I'm not having that shit, and that in DarkRP you have to think about the decision not allow it. It's on by default, because DarkRP is a non-serious sandbox gamemode. If you want to run a serious DarkRP server, you can change it in DarkRP's config. 

Sv_allowcslua isn't sv_cheats. There's a whole bunch of lua scripts still around that are really useful or fun without giving the players unfair advantage. I've always argued that blocking cslua altogether is not the solution. Block things like aimbots, ESPs and xrays specifically if you don't want players to have an unfair advantage, don't just disable it all and take out an entire community of scripts as collateral damage.

**Comment by Kefta** [comment]
``Block things like aimbots, ESPs and xrays specifically``

And how do you do that without admins constantly monitoring players?

**Comment by Noiwex** [comment]
@Kefta by having good faith in players, apparently.

**Comment by Noiwex** [comment]
Falco's small Scripts

Key features include:
- Falco's ESP (Use for RP!)
- FSpectate (Use for admin purposes!)
- Cool Xray
- Draw where players are looking
- Rotating 180 degrees
And much more!

Oh boy, sure users of your clientside scripts will use it as you said 😂

Any good server disables sv_allowcslua. If you want to allow clientside scripts you've got to make your own server, but please, don't push it down throats of DarkRP users, especially new ones.

You've put this setting on 74th line with some vague description, fooling people that it can do no harm.

But who are we kidding, custom HUDs and "build aid tools"?

**Comment by FPtje** [comment]
@Kefta block functions like setting one's own eye angles and that sort of shit. There are plenty of opportunities there. You can change the cat and mouse game of bypassing sv_allowcslua to a cat and mouse game of bypassing clientside restrictions.

@Noiwex changing a default is not pushing unless you reason that Garry pushed it on every server ever in the times of scriptenforcer and then pushed its opposite with the update that traded scriptenforcer with sv_allowcslua. It's a god damn default, and to me it's the god damn sensible default.

And the description of the option is infinitely better than Garry's silent order 66 on the clientside scripting community when he pushed that patch.

**Comment by Kefta** [comment]
The thing is that it is not a cat-and-mouse game - there are some functions that could arguably be used for legitimate purposes or for cheats, and you would have to very carefully and painstakingly remake all clientside code sent from the server not use overrided versions of problematic functions. Not to mention there are a number of ways to get built-in versions of Lua functions before or after being overrides occur, such as just overriding the default init.lua and bypassing all server-enforced logic.

The best medium would be to set sv_allowcslua to 0 but have a way for players to load custom scripts in a sandboxed and heavily restricted environment.

**Comment by FPtje** [comment]
I'm open for addons or features in gmod that implement such a sandbox.

For your former argument, that applies to Lua addons, I'm sure there can be some separation between scripts rum clientside and clientside scripts sent by the server in Gmod itself. One way to do that is through the sandbox you described.

**Comment by Kefta** [comment]
Would you be open to a pull-request that replaces the sv_allowcslua default?

**Comment by FPtje** [comment]
No, since the sandboxes you described don't exist (yet).

**Comment by Kefta** [comment]
I meant that a sandbox would be implemented into DarkRP to replace the sv_allowcslua setting.

**Comment by FPtje** [comment]
Such a sandbox would be better as a separate addon, since it would benefit many other gamemodes besides DarkRP.

**Comment by cannon** [comment]
I see, thanks. In my view it would be better for the server to install whatever useful clientside scripts are desired, maybe with option to disable. That way the experience is uniform to all players. A server's codebase can override Gmod functions which makes CS scripts that work in vanilla Gmod not work on the server, or break stuff. I see the downside though that it takes control away from players to prevent scripting.
