### ISSUE TITLE
Phrases not translated

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2837]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
"lottery" + "you" in the lottery module is not translated.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
none

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
none

**Comment by FPtje** [comment]
Lazy fix

The problem here is the big design error where I wanted to re-use sentences and make shit fill-in. That's just not portable to other languages. The best way to do translation is to translate entire phrases, even it means you end up rewriting the same subphrase over and over.

Using the Nick instead of "you" is a really easy solution here, also for the translators, as it shouldn't require any work on their part.

**Comment by mcNuggets1** [comment]
"lottery" is still not translated, but i dont know if you'll translate this one.
