### ISSUE TITLE
Hook for FSpectating

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2839]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
There currently is no a hook, when someone begins spectating another via FSpectate.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
not a bug

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
FSpectate is their addon.

**Comment by FPtje** [comment]
Why do you want these hooks? One of FSpectate's defining feature's is the anonymity. I'd rather not have hooks be used to tell clients about an admin spectating, even if those clients are superadmin/owner.

**Comment by mcNuggets1** [comment]
it should be serverside, when someone begins to spectate.
so I can integrate it into my logging system.

**Comment by FPtje** [comment]
That's exactly what I'm trying to prevent here. That's a means of telling other clients (specifically, other admins) that someone is spectating. This will make it VERY hard for server owners to catch other admins abusing their powers.

Spectating should not be logged. FAdmin has a logging system, FSpectate was always kept out of it for the above stated reason, even when it was a part of FAdmin.

**Comment by mcNuggets1** [comment]
I meant a serverside only hook, which no client at all can do anything with.
There is no abuse potential there.

**Comment by FPtje** [comment]
Surely your (super)admins can review the logs? What else are you making a logging system for?

**Comment by mcNuggets1** [comment]
How is it abuseable when it's only for preventing abuse with showing these specific logs.
There is no abuse potential at all and it would only affect server owners which manually hook into these server side hooks to run lua.

I dont see any sense in declining this request.

**Comment by FPtje** [comment]
I'm not convinced spectating is something that _can_ be abused.

To further explain the reason to decline this request, let's say you have your hook, and you implement your logging system. Then this happens:

Admin A picks up random people and throws them off roofs
Player X reports admin abuse to Owner
Owner starts spectating Admin A
Admin A keeps an eye on the logs, sees that Owner is spectating them
Admin A is nice to everyone
Owner stops spectating Admin A
Admin A throws Player X off the roof a million times for telling on them


Spectating should be anonymous. It stops being anonymous when it's logged. The whole reason why FSpectate exists in the first place is because I was always able to tell admins were spectating me or other people with a clientside script. Sure, an admin mod's logging system won't tell _every_ client, but telling other admins is bad enough.

**Comment by mcNuggets1** [comment]
That depends on the implementation of said logs.
You can still restrict logs about admins to superadmins or the owner themselves.

Also it's a selfmade implementation, it's not a core feature of fspectate, it should just be there to allow me modification.

For example if an moderator spectates the owner and the owner dislikes this behaviour, there is no way to tell, they did it.
That's abuse potential.

It's all about the implementation
I currently override playersay and your function, but with a hook, i coult stop doing it.

**Comment by FPtje** [comment]
Very well then.

**Comment by mcNuggets1** [comment]
Maybe one for teleporting either.

**Comment by FPtje** [comment]
Done

**Comment by mcNuggets1** [comment]
You merged an older version with a newer version, regressing a lot of stuff and also breaking a lil bit of darkrp configurability.
