### ISSUE TITLE
SQL table player information doesn't make any sense

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2897]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
It's a table full of steamid64s and uniqueids, yet it doesn't serve any purpose.
The table is never read from, just written to.

**Comment by Kefta** [comment]
Where specifically? What functions?

**Comment by mcNuggets1** [comment]
In DarkRP the table is to be found twice.

The Create schema and the REPLACE INTO schema.
But it never reads from it in any way.
It also doesn't make any sense tbh.

**Comment by Kefta** [comment]
Yeah you're right, it's never read by the gamemode. Maybe it's for backwards compatibility with something? Should be added as a comment/documentation if so.

**Comment by mcNuggets1** [comment]
Removing it wouldnt break compatibility I believe.

**Comment by Bo98** [comment]
This is intentional. It was a feature request from #819.

The idea was for compatibility with other addons since DarkRP used UniqueID at the time. Since then, we've moved away from using UniqueID, though there is still backwards compatibility support for it in darkrp_player.

The use case was something like this `SELECT rpname FROM darkrp_player JOIN playerinformation ON darkrp_player.uid = playerinformation.uid WHERE playerinformation.steamID = <whatever>`. This still should work today.

(Though I would argue that this level of internal implementation shouldn't really have been exposed as an API and therefore shouldn't be something we worry about backwards compatibility for with other addons. Database schemas should always be an "internal detail" and there should be freedom to migrate while not worrying about addons that decide to operate on the database directly.)

**Comment by mcNuggets1** [comment]
How about then we make it a config option?
I don't like unnecessary data written to my database.

**Comment by Bo98** [comment]
> I don't like unnecessary data written to my database.

You'll be shocked to know then that every player has two darkrp_player entries, for backwards compatibility reasons.

> It's not even documented.

At this point, I'd rather it stay that way as if it is decided that it remains then we can probably call it deprecated.

**Comment by mcNuggets1** [comment]
Wait?
I thought darkrp was saving via steamid64 but checks for compatibility reasons for both steamid and uniqueid.

**Comment by Bo98** [comment]
It does insert both in order to achieve full backwards compatibility. Here's one of the commits in the migration process: https://github.com/FPtje/DarkRP/commit/8e37e9683add293694fa0819e219383ab8c87a4e

**Comment by Bo98** [comment]
Also back then, `rpname` was unique back then so we had some pretty humourous workarounds:

https://github.com/FPtje/DarkRP/blob/61fa0c28c961aa1391dde1147d4f51c5dffa75a4/gamemode/modules/base/sv_data.lua#L268

Of course, this workaround is now gone.

**Comment by mcNuggets1** [comment]
Ah, thanks for concluding those informations.
I guess, I'll wait for FPtje to decide what to do with the playerinformation table then.

**Comment by FPtje** [comment]
I'd say document it and leave it in. We know that the people from #819 at least will find themselves with broken stuff when removed.

A config option is no-go. Configuration options are for settings that are sensible to change, not to change implementation details.
