### ISSUE TITLE
Turning all lists into hashtables ?

### ISSUE THREAD

**Issue by ExtReMLapin** [FPtje/DarkRP#2981]
More a discussion than an issue.

Everytimes table.HasValue is used, it could be turned into a hashtable that would boost performances.

Would it be fine to get rid of all table.HasValue calls and change the "data model".

To ensure retro-compatibility we could easily add a wrapper in entities/jobs creations to turn values into keys (while keeping the values to ensure compatibility with addons still reading the values instead of the keys).

**Comment by FPtje** [comment]
Indexing tables may not necessarily be faster than using `table.HasValue`, specifically when the table doesn't have many items. IIRC, Lua stores tables with indices starting from 1 and not skipping any numbers as actual arrays. Looping through a table with just a couple of dozen items might be faster than indexing. Even though `table.HasValue` is `O(1)` and indexing is `O(1)`, the constant factor of the indexing (i.e. in the hashing of the key) might be slower than walking through the table.

I don't know which is faster, I'll need proof either way.

Besides, most places where we use `table.HasValue`, is in data structures that are most likely used by third party addons, like `GAMEMODE.Config.DefaultWeapons`, `RPExtraTeamDoors`, job/shipment attributes (`weapons`, `NeedToChangeFrom`, `allowed`).

I'll argue that the pain and misery caused by breaking a ton of addons is not worth the minor optimisation. Especially when it's not even argued to be a bottleneck anywhere.

**Comment by ExtReMLapin** [comment]
With the retrocompatiblity patches added on entity creation

Lua PUC (doesn't apply to gmod) performances : 

```
List time : 1.628372
HashTable time : 0.604586
```

**169.34 %** performance boost

LuaJIT 2.1.0-beta3 (github version)

```
List time : 0.510123
HashTable time : 0.014414

```
**3439.08 %** performance boost

And that's only for a short list 


```Lua

local TEAM_POTATO = 42
local TEAM_TOMATO = 66
local TEAM_BREAD = 3
local TEAM_COWBOY = 1
local TEAM_PANCAKE = 2



local listTeam = {
	TEAM_POTATO,
	TEAM_TOMATO,
	TEAM_BREAD,
	TEAM_COWBOY,
	TEAM_PANCAKE,
}

local specialTeam = {
	[TEAM_POTATO] = true,
	[TEAM_TOMATO] = true,
	[TEAM_BREAD] = true,
	[TEAM_COWBOY] = true,
	[TEAM_PANCAKE] = true
}


function table.HasValue( t, val )
	for k, v in pairs( t ) do
		if ( v == val ) then return true end
	end
	return false
end


function hashTableFind(t, val)
	return t[val] == true
end


local max = 5000000

do
	local time = os.clock()
	for k, v in ipairs(specialTeam) do
		local i = 0

		while (i < max) do
			table.HasValue(specialTeam, v)
			i = i + 1
		end
	end
	print("List time : " .. os.clock()-time)
end


do
	local time = os.clock()
	for k, v in ipairs(specialTeam) do
		local i = 0

		while (i < max) do
			hashTableFind(specialTeam, v)
			i = i + 1
		end
	end
	print("HashTable time : " .. os.clock()-time)
end
```

**Comment by ExtReMLapin** [comment]
I deleted my last message, as I did a mistake in the benchmark code


LuaPUC : 

```
List = 0.045553s
Hashtable = 0.010750s
Perf boost 323.748837%

```


LuaJIT : 

```
List = 0.013691s
Hashtable = 0.000267s
Perf boost 5027.715356%
```



```Lua

local function genTableAndHashTable(size)
	local hash = {}
	local list = {}
	local i = 1
	while (i <= size) do
		hash[i] = true
		list[i] = i
		i = i + 1
	end
	return list, hash

end


local testSize = 5

local specialTeam, hashtable = genTableAndHashTable(testSize)


local time1, time2
function table.HasValue( t, val )
	for k, v in pairs( t ) do
		if ( v == val ) then return true end
	end
	return false
end


function hashTableFind(t, val)
	return t[val] == true
end


local max = 50000

do
	local time = os.clock()
	for k, v in ipairs(specialTeam) do
		local i = 0

		while (i < max) do
			table.HasValue(specialTeam, v)
			i = i + 1
		end
	end
	time1 = os.clock()-time
end


do
	local time = os.clock()
	for k, v in ipairs(specialTeam) do
		local i = 0

		while (i < max) do
			hashTableFind(specialTeam, v)
			i = i + 1
		end
	end
	time2 = os.clock()-time
end


print(string.format("List = %fs", time1))
print(string.format("Hashtable = %fs", time2))
print(string.format("Perf boost %f%%", ((time1-time2)/time2)*100))


```

**Comment by FPtje** [comment]
So when run 50k times, a significantly faster performance is measured with table indexing. I'm not convinced that performance increase translates well to the real situation where the `table.HasValue` is run at most a couple of dozen times when someone runs a chat command.

> To ensure retro-compatibility we could easily add a wrapper in entities/jobs creations to turn values into keys

There are several interests that need to be balanced in any programming project: 
- Performance, but also
- Code complexity
- Code readability
- Backwards compatibility
- Functionality

You can keep two datastructures for backwards compatibility, but the problem with that is that you then have two datastructures that must remain in sync. I'm not sure if you've ever heard of the joke of the [two hard things in computer science](https://twitter.com/codinghorror/status/506010907021828096?lang=en), but cache invalidation there is one of them, and for a good reason. It's really easy to quickly hack up something together that translates the list to a key-value table, but it's usually extremely hard to be 100% sure that there's no place that updates the list, but not the key-value table. 

That adds a lot of complexity to the code. Assuming that your performance measurement can be divided, and assuming e.g. 100 calls to `table.HasValue` per frame/chat command/whatever, we would be talking about a performance increase of `(0.013691 - 0.000267) / 500 = 0.000026848`. That's taking the LuaJIT performance difference of 5027%. The `500` is from the `50000` calls translated to 100 calls. 

Obviously this is a very rudimentary calculation, but it shows the ballpark of where we're at.

**Comment by Kefta** [comment]
It's actually less complex to use hashtables than sequential ones, and your backwards compatibility problem is solveable by having a parallel hashtable for accesses. There's no issues with cache invalidation because they can be updated simultaneously by a local function or a metatable __newindex wrapper if you're handing out table references. You could even store the hash portion in the same array.

The reason why people are so concerned with these seemingly minute performance improvements is that even with perfectly optimised addons and major bottlenecks addressed, the game still runs like shit on 64+ player servers. Any slots above that requires major base gamemode and DarkRP optimisations to have a stable server, which is necessary to compete in the DarkRP category. Most communities who pull 100+ players regularly per server aren't even using this gamemode or much of GMod's base code. Though DarkRP has a lot of backwards compatibility necessities, there is still much room for improvement on basic Lua habits for constant-time optimisations and fully utilising LuaJIT.

This gamemode is also how a lot of new developers gets started, so implementing efficient habits in the code sets a good precedent.

**Comment by FPtje** [comment]
>  solveable by having a parallel hashtable for accesses. There's no issues with cache invalidation because they can be updated simultaneously by a local function or a metatable __newindex wrapper if you're handing out table references.

Like I said, that's easy enough to create, very hard to be certain that it always stays in sync. It's possible like you said, by creating an abstraction on top of the data structures, but if you want to set a good precedent for new developers, having little complexity is also a major goal. 

> with perfectly optimised addons and major bottlenecks addressed, the game still runs like shit on 64+ player servers.
If the game runs shit, then necessarily there must be a bottleneck. Trying to solve real performance problems with micro-optimisations is like trying to stop a flood by putting river water in buckets. 

We can go hellbent on all the micro-optimisations, spend literal *years* on finding and fixing things that will each give `0.000026848` seconds increase per frame. I can easily predict that 5 years down the line of going full anal, you will have achieved exactly **jack shit**. People who know what they're doing take a structured approach of optimising. That involves the following development loop:

- Profile
- Identify Bottleneck
- Attack bottleneck
- Profile, measure effect on bottleneck
- If there's different bottleneck, go to step 2, otherwise, go to step 3.

Any other approach **demonstrably** leads to a waste of time. Time in any game loop is not spent equally, there's always a biggest factor. Attacking anything else will lead to negligible performance increases.

https://wiki.c2.com/?ProfileBeforeOptimizing

The past has proven that micro-optimisations are a really good way to introduce bugs. Those bugs cause more pain than the negligible performance increases have relieved.

Build some good profiling tools, use existing ones. Find the answer to what code path the **real** cause is for servers bogging down with 64+ players.

**Comment by ExtReMLapin** [comment]
> on basic Lua habits for constant-time optimisations and fully utilising LuaJIT.


Tbh you can forget about the jit compiler with gmod in 90% of the cases because traces won't happen with C API calls.

Even if Very last version of luajit adds stitching, it won't help a lot.
