### ISSUE TITLE
createMoneyBag doesn't work

### ISSUE THREAD

**Issue by feelingnothing** [FPtje/DarkRP#3022]
### Description of the bug
[//]: # createMoneyBag doesn't work

### How to make the bug happen
[//]: # passing clear(not overrided) self:GetPos()) into DarkRP:createMoneyBag

### Lua errors
type of entity pos: Vector
[DarkRP] gamemodes/darkrp/gamemode/modules/money/sv_money.lua:42: bad argument #1 to 'SetPos' (Vector expected, got table)
  1. SetPos - [C]:-1
   2. createMoneyBag - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:42
    3. unknown - addons/entity/lua/entities/printer/init.lua:25

### My Code
local pos = self:GetPos()
print('type of entity pos: '..type(pos))
DarkRP:createMoneyBag(Vector(pos.x + 15, pos.y, pos.z + 15), self.amount)

**Comment by Kefta** [comment]
Because you're calling it like ``DarkRP:createMoneyBag`` instead of ``DarkRP.createMoneyBag``, thus you're passing the DarkRP table as the first argument, not a Vector. You could have just commented on your previous issue instead of creating a new one. This is not a help repo, use https://forum.darkrp.com/ in the future.
