### ISSUE TITLE
Doubling Data

### ISSUE THREAD

**Issue by Zulbem** [FPtje/DarkRP#3026]
Hello!

Inside sv.db, the category darkrp_player contains double information for each player, one with their steamid and one with their unique id both under "uid" column, what's up with that? I have the latest version installed.

**Comment by FoksVHox** [comment]
I assume it’s a primary key, for indexing, even tho it would be perfectly fine without it

**Comment by FPtje** [comment]
It's a backwards compatibility thing. Back in the day darkrp used a function `ply:UniqueID()` to store as primary key in the database. That UniqueID turned out not to be that unique. Servers were getting players that would end up sharing the same row in the database. They would have the same amount of money, same rp name etc.

I changed the id function, but for backwards compatibility still also had to work with UniqueID. That causes double data. 

I guess that code can be removed now though.

**Comment by FPtje** [comment]
Oh wait no, addons were using that data as well. Some were probably never converted. This will remain there for compatibility.

**Comment by Bubka3** [comment]
Sorry if this is not allowed (or if anyone even looks at closed issues) but going forward ``ply:SteamID64()`` is the "modern" way to store a player's steam ID right?

**Comment by Kefta** [comment]
Yes.
