### ISSUE TITLE
DarkRP - cannot pocket world entities under any circumstances

### ISSUE THREAD

**Issue by Alex2259** [FPtje/DarkRP#3082]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
World entities cannot be added to the DarkRP pocket. This in spite of what is/isn't in the blacklist, or if items in the blacklist are set to "True." This includes items that players can spawn via the F4 menu that we may desire to be pocketed, or various other entities. Entities we force to be owned by the player via LUA seem to work fine, but that doesn't encompass everything. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Spawn an entity via F4 menu or from an adon (ex. weed plant) and attempt to pocket it. Removing an item from the pocket also sometimes "resets" the entity's ownership (so, if it was able to be pocketed at one point, after removing it from your pocket it cannot be re-pocketed.) Applies to any entity that is under "world" - but player-owned entities are able to be pocketed unless they're on the blacklist. 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
In my estimation, this is an issue with the game mode's pocketing feature (which we like to use due to the fact it "just works" normally, and isn't as convoluted as many inventory systems) If you believe this is an issue specific to our config, feel free to close.

**Comment by FPtje** [comment]
It is probably best to look at "Use Protection" settings of your prop protection (probably FPP). You can try disabling it entirely, see if that solves the problem. If it doesn't, then something else might be amiss. If it does work (which I suspect), then tweaking the use settings should help you fix the pocket issue.

The pocket tool changing ownership of things is something I cannot produce on my own installation. Something else might be broken here.

I'm closing the issue, also because this issue tracker is not for support, but please post a reply to this issue if temporarily disabling the use protection does not change anything.

**Comment by Alex2259** [comment]
A third party prop protection addon called "GProtect" is causing this issue.
