### ISSUE TITLE
Darkrp Error

### ISSUE THREAD

**Issue by DydyGames** [FPtje/DarkRP#3108]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

The TAB menu is bug and we see only the steam name, not the rp name

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
When someone connect on my server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[DarkRP] gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:85: attempt to index a nil value
  1. readNetDarkRPVarRemoval - gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:85
   2. func - gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:46
    3. unknown - lua/includes/extensions/net.lua:32

[DarkRP] gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:78: attempt to index local 'DarkRPVar' (a nil value)
  1. readNetDarkRPVar - gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:78
   2. func - gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:34
    3. unknown - lua/includes/extensions/net.lua:32

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

maybe " 'DarkRPVar' "

**Comment by FoksVHox** [comment]
Do you have any addons installed, if so remove them. There might be one of them that is causing these issues.

**Comment by DydyGames** [comment]
I have a community and I can't afford to remove all the addons for a whole day ... The bug appears when we reach around 10 players ..

**Comment by FlorianLeChat** [comment]
This is most likely a problem on your side. If you don't do anything to test on your side, you will waste time for nothing because Falco will just tell you there is no problem with a vanilla DarkRP. Also, before opening an issue on Github, I recommend you to first ask this question on the DarkRP Discord: https://darkrp.page.link/discord.

**Comment by FPtje** [comment]
The error would indicate that there is at least one DarkRPVar that is registered on the server, but not the client. There are two reasons why this could happen:

- DarkRP fails to load fully on the client. You will see this when joining the server, you will find errors in console.
- Some other addon is at fault, using DarkRPVars, but not properly. You said happens when you reach around 10 players. There is probably a specific event that causes this to happen. Some player doing something, someone running a command, an entity doing something. One hint I can give you here is that the error is about a DarkRPVar being removed from a player. That could mean it happens when some event "stops", though it might not. Pinpointing what triggers the error is your best chance at finding the addon that causes this fast.


Good luck finding the issue.


> Falco will just tell you there is no problem with a vanilla DarkRP

Well in this case I can give a couple of hints...
