### ISSUE TITLE
AddCSLuaFile with interfaceloader

### ISSUE THREAD

**Issue by retrime** [FPtje/DarkRP#3136]
### Description of the bug
Seems like cl_init.lua and interfaceloader.lua both loading AddCSLuaFile

**Comment by FPtje** [comment]
What exactly do you mean by "loading `AddCSLuaFile`"?

**Comment by retrime** [comment]
I mean gamemode cl_init.lua will do AddCSLuaFile and interfaceloader will also do AddCSLuaFile on the same file

**Comment by retrime** [comment]
Like AddCSLuaFile twice for 1 file

**Comment by FPtje** [comment]
Are you sure? `interfaceloader.lua` only runs it on `{sh|sv|cl}_interface.lua` files:

https://github.com/FPtje/DarkRP/blob/25d85493ac51329a2556567492917f6b8524a278/gamemode/libraries/interfaceloader.lua#L182

`cl_init.lua` doesn't call `AddCSLuaFile` (because `AddCSLuaFile` is a serverside function, and `cl_init` is clientside)

and `init.lua` excludes any `{sh|sv|cl}_interface.lua` files:

https://github.com/FPtje/DarkRP/blob/25d85493ac51329a2556567492917f6b8524a278/gamemode/init.lua#L88
https://github.com/FPtje/DarkRP/blob/25d85493ac51329a2556567492917f6b8524a278/gamemode/init.lua#L93
https://github.com/FPtje/DarkRP/blob/25d85493ac51329a2556567492917f6b8524a278/gamemode/init.lua#L98

**Comment by retrime** [comment]
Oh sorry, I mean init.lua file on line 87

**Comment by retrime** [comment]
While interface skip is on 88 line, it will do AddCSLuaFile anyway

**Comment by FPtje** [comment]
Ah yes, well spotted
