### ISSUE TITLE
Collation mysql error

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#3157]
I have updated the collation to utf8mb4, and this error appears in the darkrp_doorjobs table

https://i.gyazo.com/db02055fa15eca1bc93eb8c94e04a011.png

Server mysql: 5.7.31
Collation: utf8mb4_unicode_ci
Module: Mysqloo 9.7.2

**Comment by WilliamVenner** [comment]
utf8mb4_unicode_ci is 4 bytes per character maximum, so every VARCHAR's size becomes VARCHAR(x) = x * 4 which is why the error is ocurring.

The collation isn't really supposed to be used globally for this reason, for example the map key there could easily get away with just being ASCII.

The solution is to just increase the maximum key size, if you want to use this collation.

**Comment by FPtje** [comment]
I can understand wanting to use 4 byte utf-8 though.

Judging by this answer: https://stackoverflow.com/a/1814594, you can set the engine to innodb to fix your issue. The limit of 1000 is a myisam thing. You can switch the engine of a table with an alter table query:

```
ALTER TABLE my_table ENGINE = InnoDB;
```

Fill in DarkRP tables for my_table.

As for what DarkRP should do, I'm not sure. I'm not lowering the varchar limit. That would break things for many people. I'm not sure if I should switch the tables to innodb. I don't know if that might break some people's use cases. I'll look into the general differences between myisam and innodb. All I know right now is this difference in limits, and a distant memory about something to do with enforcing foreign keys. The latter might actually be a problem if people's databases already have inconsistent data. If servers suddenly start erroring with foreign key errors, that's no bueno.

**Comment by matiasg90** [comment]
I recently upgraded from ulx to sam, and when importing data it threw errors, I talked to the SAM programmer and we realized that the problem was the database collation.

that way, I decided to set the mysql server as the default, which by the way the default mysql server uses utf8mb4, and no longer utf8, Sooner or later, users will have to upgrade to utf8mb4

or what collation do you recommend using darkrp?

**Comment by FPtje** [comment]
Yes, that's the maximum amount of characters allowed in the database. If strings are larger, you get errors.

**Comment by matiasg90** [comment]
as it is about that only table (darkrp_doorjobs)
I don't think I have a problem, since the names of the jobs are extremely few characters

I have lowered the varchar and the error stopped appearing
anything that happens I will let you know

**Comment by FPtje** [comment]
> that way, I decided to set the mysql server as the default, which by the way the default mysql server uses utf8mb4, and no longer utf8, Sooner or later, users will have to upgrade to utf8mb4

Looks like the default database engine has been InnoDB for quite a while. I think the biggest technical debt here is that you were on MyISAM. I'm working on having DarkRP migrate every table to InnoDB. DarkRP tables don't have foreign keys, so it should be fine.

Though I would expect you would get the same error with `FAdmin_CAMIPrivileges`, which also has a `VARCHAR(255)` error. I know I get the error when I try to switch the table to MYISAM (for me the tables were created with InnoDB because I use MySQL 8)

**Comment by FPtje** [comment]
Alright, I've added a migration to move the DarkRP tables to innodb. Please update DarkRP to run this migration. It should be compatible with your change to lower the varchar limit, but it means you can change it back to what it was.

There are a bunch more places where tables are created, including the mentioned FAdmin ones, but they don't have a migration mechanism. Let's wait with migrating those until they become a problem. 

Note to self when deciding to migrate the other table to InnoDB: the `FADMIN_PRIVILEGES` table has a foreign key, so before setting the engine to InnoDB, a query should remove all items from it that don't have a matching row in `FADMIN_GROUPS`.
