### ISSUE TITLE
Payday timer error

### ISSUE THREAD

**Issue by SendLua** [FPtje/DarkRP#3174]
![image](https://user-images.githubusercontent.com/75088221/169682260-df4feccb-8795-4af4-9a5f-3aa8c7ff08e0.png)

**Comment by SendLua** [comment]
This error happens after changing config.lua

**Comment by SendLua** [comment]
fix - https://github.com/FPtje/DarkRP/pull/3175

**Comment by FPtje** [comment]
It looks like your `gamemode\modules\money\sv_money.lua` file was modified. The error you post is impossible in DarkRP itself. The error mentions performing arithmetic on a nil value. Arithmetic here means adding numbers, subtracting, dividing, etc. The place where this supposedly happens, `gamemode\modules\money\sv_money.lua` line 9, does no such thing. Because of this modification, I cannot fix this DarkRP. After all, it's not broken in the official version of DarkRP.

On There _is_ arithmetic on line 8. I'm guessing there's a change that this might be your line 9. For the official version, this is what the first 15 lines look like:

https://github.com/FPtje/DarkRP/blob/a84a00cf99a510a4c25bd50ef428c2522ce65d63/gamemode/modules/money/sv_money.lua#L1-L15

If this line 8 is your line 9, then I think your problem is not in this file. Something probably causes DarkRP to fail to load. In that case look at the _earlier_ error you see when you start your server. That error probably happens before anyone joins. 

As for this issue, there isn't anything else I can do to help. I'm closing the issue.
