### ISSUE TITLE
Wiki down

### ISSUE THREAD

**Issue by mark27205** [FPtje/DarkRP#3208]
Please check out the wiki, as it is not reachable.

**Comment by FPtje** [comment]
For updates, we can monitor the following page: https://meta.miraheze.org/wiki/Tech:SRE_noticeboard

**Comment by luca1197** [comment]
According to an update from yesterday in the noticeboard, they are working to get the wiki back online, sounds great!

For the meantime, I found a backup I made in January this year and quickly threw together a small website to navigate it. My backup just consisted of exported pages of [Wikitext](https://meta.wikimedia.org/wiki/Help:Wikitext_examples) that are quite difficult to parse because I am missing the required templates, but it should be better than nothing for now: https://darkrp-wiki.lucaaa.xyz/

I hope that helps a bit!

**Comment by FPtje** [comment]
Awesome. Thanks!

**Comment by FPtje** [comment]
Looks like the wiki is back up, yay!
