### ISSUE TITLE
FAdmin fails to load in singleplayer for upcoming update

### ISSUE THREAD

**Issue by CyberSamurai0** [FPtje/DarkRP#3227]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Unknown issue causes fadmin to error on initial load, in turn breaking the default scoreboard
Does not occur on stable version as of 06/22/2023
Untested on multiplayer

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Used latest commit of FPtje/DarkRP and FPtje/darkrpmodification.
Launched singleplayer on any map with fadmin enabled

Persists with `-noaddons` and `-noworkshop` after Garry's Mod factory reset
Tested and verified on Windows using the following betas
- x86-64
- prerelease
- dev

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
```
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/rcon/cl_init.lua:5: attempt to call method 'AddServerAction' (a nil value)
  1. v - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/rcon/cl_init.lua:5
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/sh_fadmin_darkrp.lua:80

Timer Failed! [Simple][@gamemodes/darkrp/gamemode/modules/fadmin/sh_fadmin_darkrp.lua (line 77)]
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Presumably an issue caused by the upcoming June update, perhaps a mistake on the official developers' part.
If they broke some core functionality, you would need to take it up with them to get it resolved, as you would know far better than I do what's wrong.
If they made a change that wasn't in error, you would need to adjust your code to accommodate it.

**Comment by FPtje** [comment]
An update breaking darkrp? That hasn't happened in many, many years! Thanks for reporting!

From just a glance at the error, it seems that something might have changed in loading Lua files. Maybe the order changed, or some files are not being loaded at all. I'd have to look deeper to confirm, though.

There's one change that might be related:

> Experimental: Completely removed Lua file limit for singleplayer

https://wiki.facepunch.com/gmod/Update_Preview_Changelog

In this context I think the above error would be a bug in that change, if it is indeed caused by it. 

@Kefta do you happen to know what might be going on here, or who might be able to chime in on the issue? I have to admit I haven't been keeping track of gmod updates and who works on them. Thanks!

**Comment by Kefta** [comment]
I wouldn't think that change (nor any from this update) would cause any breakages, but I will test fadmin this week when I have the time to see if I can narrow down why the error happens.

**Comment by FPtje** [comment]
Much appreciated, thanks!

**Comment by FPtje** [comment]
Looks like the update is released, and I can definitely reproduce the error. At least on Linux. The error does not reproduce when I select any option other than single player (tested with selecting 32 players)

The function in the error is nil on singleplayer after loading. It exists when starting a multiplayer server.

@robotboy655 I can confirm DarkRP is broken in singleplayer since at least the latest update. I don't know if previous versions were broken, but this one definitely is. Could you look at this?

**Comment by robotboy655** [comment]
You are still on yesterday's version, I don't think the game build worked, sorry, seems GitHub Actions shit the bed a bit.

It should be good to go now however.

**Comment by FPtje** [comment]
Seems to work now. Thanks!
